// SPDX-License-Identifier: AGPL-3.0-or-later
#pragma once

#include "makehuman/foundation/Transform.h"
#include "makehuman/io/BvhReader.h"
#include "makehuman/rig/Skeleton.h"

#include <expected>
#include <filesystem>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace mh::rig {

using foundation::Mat4;

/// A library of named unit poses, each a full set of per-bone transforms.
///
/// The face library ships as a BVH of 60 frames plus a JSON `framemapping`
/// naming them; frame N is the pose named N. A unit is a single expression
/// component ("LeftBrowDown"), and an expression is a weighted blend of them.
struct PoseUnits {
    std::vector<std::string> names;
    size_t boneCount{};

    /// names.size() * boneCount transforms, unit-major.
    std::vector<Mat4> data;

    [[nodiscard]] size_t unitCount() const noexcept { return names.size(); }

    [[nodiscard]] std::span<const Mat4> unit(size_t i) const {
        return {data.data() + i * boneCount, boneCount};
    }

    [[nodiscard]] std::optional<size_t> indexOf(std::string_view name) const;

    /// Blends units together, weighted.
    ///
    /// **This is order-dependent, deliberately.** Each unit is turned into a
    /// rotation scaled by its weight -- `slerp(identity, q_i, w_i)` -- and the
    /// results are composed by multiplication:
    ///
    ///     quat = q1;  quat = q2 * quat;  quat = q3 * quat;  ...
    ///
    /// Quaternion multiplication does not commute, so feeding the same units in
    /// a different order gives a different face. Measured on the shipped units:
    /// reversing a five-unit blend moves the result by **0.034**. The reference
    /// behaves this way (`animation.py:402-415`) and expression files are
    /// authored against it, so it is replicated rather than "fixed" by
    /// symmetrising.
    ///
    /// Weights are **not** normalised: the blend is additive, so two units at
    /// 1.0 apply both fully rather than averaging to a half of each.
    ///
    /// @return boneCount transforms, or empty if the inputs disagree in length
    ///         or an index is out of range.
    [[nodiscard]] std::vector<Mat4> blend(std::span<const size_t> unitIndices,
                                          std::span<const float> weights) const;
};

/// One unit of an expression, and how much of it to apply.
struct WeightedUnit {
    std::string name;
    float weight{};
};

/// A `.mhpose`: a named, weighted set of pose units.
///
/// The expression mixer writes this format
/// (`plugins/7_expression_mixer.py:221-238`) and `Pose.fromPoseUnit` reads it
/// (`shared/animation.py:286-309`) -- the same JSON either way, which is why
/// the `.mhupb` the reference's parser names and the `.mhpose` its writer emits
/// are one thing.
///
/// `units` keeps the FILE's order. The blend multiplies quaternions and does
/// not commute, and the reference hands `list(unit_poses.keys())` straight to
/// it, so sorting or de-duplicating here would produce a different expression
/// from the one that was authored.
struct Expression {
    std::string name;
    std::string description;
    std::vector<std::string> tags;
    std::vector<WeightedUnit> units;
};

enum class PoseUnitsErrorKind { NotFound, Unreadable, Malformed, FrameCountMismatch };

struct PoseUnitsError {
    PoseUnitsErrorKind kind{};
    std::string file;
    std::string detail;

    [[nodiscard]] std::string message() const;
};

/// Reads a `.mhpose` expression file.
///
/// **No `.mhpose` ships with MakeHuman**, which is why this was filed for a
/// year as machinery with nothing to test it. The fixture is generated by the
/// reference instead (`tools/capture_fixture.py mhpose`): written in the shape
/// its own writer produces and blended by its own `getBlendedPose`.
///
/// Two refusals are the reference's (`animation.py:296,301-302`), kept rather
/// than softened: a missing `name` raises there, and an empty `unit_poses`
/// raises "needs to contain at least one entry". A file naming no units is one
/// someone meant to fill in, not a neutral expression.
///
/// Everything else the format carries -- description, tags, author, copyright,
/// licence, homepage -- is optional in the reference (`mhupb.get(...)`) and is
/// optional here. Unknown keys are ignored, or no file the reference has ever
/// written would load.
[[nodiscard]] std::expected<Expression, PoseUnitsError> loadExpression(
    const std::filesystem::path& path);

/// Reads the `framemapping` name list from a pose-unit JSON.
[[nodiscard]] std::expected<std::vector<std::string>, PoseUnitsError> loadPoseUnitNames(
    const std::filesystem::path& path);

/// Maps a BVH's frames onto @p skeleton's bone order to build the library.
///
/// The BVH and the rig are **not the same joint set** -- the face BVH has 212
/// joints against the rig's 163 bones -- so this walks the rig's bones and
/// takes each one's identically-named BVH joint, leaving identity where the BVH
/// has none. Walking the BVH instead would silently reorder every bone.
[[nodiscard]] std::expected<PoseUnits, PoseUnitsError> makePoseUnits(
    const io::BvhFile& bvh, const Skeleton& skeleton, std::vector<std::string> names);

/// Loads a whole-body pose -- a T-pose, an A-pose, a stance -- from a
/// single-frame BVH, ready to hand to computeSkinningMatrices().
///
/// The rest pose needs no file: it is what the mesh already is, so "A-pose" for
/// the MakeHuman base mesh is an empty span, not a pose to load. Only poses
/// that differ from the authored rest need one.
///
/// The file must hold exactly one frame. A multi-frame BVH is an animation, and
/// silently taking its first frame would turn a wrong file into a plausible
/// wrong pose.
[[nodiscard]] std::expected<std::vector<Mat4>, PoseUnitsError> loadBodyPose(
    const std::filesystem::path& path, const Skeleton& skeleton);

/// Layers @p overlay's transforms for @p bones onto @p base, leaving the rest
/// of @p base alone. This is what puts a facial expression on a posed body.
///
/// The reference (`shared/animation.py:449-467`) copies pose1 and assigns
/// pose2's rows for the listed indices; it raises when the two poses have
/// different bone counts, because mixing poses built for different skeletons
/// produces a plausible-looking wrong body. Both refusals are kept:
///
///   - differing sizes -> `FrameCountMismatch`;
///   - a bone index past the end -> `Malformed` (the reference would raise
///     IndexError; silently skipping it would drop part of the expression).
///
/// Order does not matter here and no interpolation happens -- unlike
/// PoseUnits::blend, this replaces rather than composes.
[[nodiscard]] std::expected<std::vector<Mat4>, PoseUnitsError> mixPoses(
    std::span<const Mat4> base, std::span<const Mat4> overlay, std::span<const size_t> bones);

}  // namespace mh::rig
