// SPDX-License-Identifier: AGPL-3.0-or-later
#pragma once

#include "makehuman/foundation/Transform.h"
#include "makehuman/io/BvhReader.h"
#include "makehuman/rig/RetargetMap.h"
#include "makehuman/rig/Skeleton.h"

#include <expected>
#include <filesystem>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace mh::rig {

using foundation::Mat4;

/// A library of named unit poses, each a full set of per-bone transforms.
///
/// The face library ships as a BVH of 60 frames plus a JSON `framemapping`
/// naming them; frame N is the pose named N. A unit is a single expression
/// component ("LeftBrowDown"), and an expression is a weighted blend of them.
struct PoseUnits {
    std::vector<std::string> names;
    size_t boneCount{};

    /// names.size() * boneCount transforms, unit-major.
    std::vector<Mat4> data;

    [[nodiscard]] size_t unitCount() const noexcept { return names.size(); }

    [[nodiscard]] std::span<const Mat4> unit(size_t i) const {
        return {data.data() + i * boneCount, boneCount};
    }

    [[nodiscard]] std::optional<size_t> indexOf(std::string_view name) const;

    /// Blends units together, weighted.
    ///
    /// **This is order-dependent, deliberately.** Each unit is turned into a
    /// rotation scaled by its weight -- `slerp(identity, q_i, w_i)` -- and the
    /// results are composed by multiplication:
    ///
    ///     quat = q1;  quat = q2 * quat;  quat = q3 * quat;  ...
    ///
    /// Quaternion multiplication does not commute, so feeding the same units in
    /// a different order gives a different face. Measured on the shipped units:
    /// reversing a five-unit blend moves the result by **0.034**. The reference
    /// behaves this way (`animation.py:402-415`) and expression files are
    /// authored against it, so it is replicated rather than "fixed" by
    /// symmetrising.
    ///
    /// Weights are **not** normalised: the blend is additive, so two units at
    /// 1.0 apply both fully rather than averaging to a half of each.
    ///
    /// @return boneCount transforms, or empty if the inputs disagree in length
    ///         or an index is out of range.
    [[nodiscard]] std::vector<Mat4> blend(std::span<const size_t> unitIndices,
                                          std::span<const float> weights) const;
};

/// One unit of an expression, and how much of it to apply.
struct WeightedUnit {
    std::string name;
    float weight{};
};

/// A `.mhpose`: a named, weighted set of pose units.
///
/// The expression mixer writes this format
/// (`plugins/7_expression_mixer.py:221-238`) and `Pose.fromPoseUnit` reads it
/// (`shared/animation.py:286-309`) -- the same JSON either way, which is why
/// the `.mhupb` the reference's parser names and the `.mhpose` its writer emits
/// are one thing.
///
/// `units` keeps the FILE's order. The blend multiplies quaternions and does
/// not commute, and the reference hands `list(unit_poses.keys())` straight to
/// it, so sorting or de-duplicating here would produce a different expression
/// from the one that was authored.
struct Expression {
    std::string name;
    std::string description;
    std::vector<std::string> tags;
    std::vector<WeightedUnit> units;
};

enum class PoseUnitsErrorKind { NotFound, Unreadable, Malformed, FrameCountMismatch };

struct PoseUnitsError {
    PoseUnitsErrorKind kind{};
    std::string file;
    std::string detail;

    [[nodiscard]] std::string message() const;
};

/// Reads a `.mhpose` expression file.
///
/// **No `.mhpose` ships with MakeHuman**, which is why this was filed for a
/// year as machinery with nothing to test it. The fixture is generated by the
/// reference instead (`tools/capture_fixture.py mhpose`): written in the shape
/// its own writer produces and blended by its own `getBlendedPose`.
///
/// Two refusals are the reference's (`animation.py:296,301-302`), kept rather
/// than softened: a missing `name` raises there, and an empty `unit_poses`
/// raises "needs to contain at least one entry". A file naming no units is one
/// someone meant to fill in, not a neutral expression.
///
/// Everything else the format carries -- description, tags, author, copyright,
/// licence, homepage -- is optional in the reference (`mhupb.get(...)`) and is
/// optional here. Unknown keys are ignored, or no file the reference has ever
/// written would load.
[[nodiscard]] std::expected<Expression, PoseUnitsError> loadExpression(
    const std::filesystem::path& path);

/// Writes a `.mhpose`.
///
/// The counterpart of `loadExpression`, and the missing half of the reference's
/// expression mixer: it could Save (`plugins/7_expression_mixer.py:221-238`)
/// and this port could only read, so an expression a user composed could not be
/// kept. It is also why nothing under `data/` is a `.mhpose` -- there was no
/// way to make one.
///
/// **Order is preserved, and that is the whole point.** `blend` multiplies
/// quaternions and does not commute, so `units` order is part of the
/// expression, not a presentation detail. This writes `nlohmann::ordered_json`
/// for the same reason the reader parses it: the default `json` holds an object
/// in a std::map and would emit the units alphabetically, producing a file that
/// loads cleanly into a different face.
///
/// **Zero-weight units are dropped**, as the reference drops them
/// (`7_expression_mixer.py:223`). Every slider is a modifier there, so without
/// the filter a saved file would name all 60 units and say nothing about which
/// ones were moved.
///
/// Refuses to write anything `loadExpression` would reject: an expression with
/// no name, or one left with no units once the zeros are gone. Writing a file
/// our own reader refuses is worse than failing here, where the caller can say
/// so. Nothing is created on any of those paths.
[[nodiscard]] std::expected<void, PoseUnitsError> saveExpression(const std::filesystem::path& path,
                                                                 const Expression& expression);

/// Reads the `framemapping` name list from a pose-unit JSON.
[[nodiscard]] std::expected<std::vector<std::string>, PoseUnitsError> loadPoseUnitNames(
    const std::filesystem::path& path);

/// Maps a BVH's frames onto @p skeleton's bone order to build the library.
///
/// The BVH and the rig are **not the same joint set** -- the face BVH has 212
/// joints against the rig's 163 bones -- so this walks the rig's bones and
/// takes each one's identically-named BVH joint, leaving identity where the BVH
/// has none. Walking the BVH instead would silently reorder every bone.
[[nodiscard]] std::expected<PoseUnits, PoseUnitsError> makePoseUnits(
    const io::BvhFile& bvh, const Skeleton& skeleton, std::vector<std::string> names);

/// Builds the BODY pose-unit library from `body-poseunits.json`.
///
/// The second producer of `PoseUnits`, and a different shape from the first:
/// `makePoseUnits` reads 60 frames of a BVH, while this reads 61 poses that
/// each name their bones directly as `[w,x,y,z]` quaternions. No frames, no
/// BVH. The RESULT is the same type on purpose, so `indexOf` and `blend` do not
/// care which producer made a unit.
///
/// A bone the rig does not have is left at identity, exactly as `makePoseUnits`
/// leaves an unmatched joint -- so a partially-resolving pose moves the bones it
/// can and nothing else.
///
/// @param names an optional table renaming the asset's bones to this rig's.
///        MEASURED on the 61 shipped poses: without one, 29 resolve fully, 24
///        partially and 8 not at all; with `body-poseunits-bones.json`, 36 / 20
///        / 5. The asset was authored against a differently-named skeleton, so
///        name matching alone silently drops a third of it.
[[nodiscard]] std::expected<PoseUnits, PoseUnitsError> loadBodyPoseUnits(
    const std::filesystem::path& path, const Skeleton& skeleton,
    const RetargetMap* names = nullptr);

/// Loads a whole-body pose -- a T-pose, an A-pose, a stance -- from a
/// single-frame BVH, ready to hand to computeSkinningMatrices().
///
/// The rest pose needs no file: it is what the mesh already is, so "A-pose" for
/// the MakeHuman base mesh is an empty span, not a pose to load. Only poses
/// that differ from the authored rest need one.
///
/// The file must hold exactly one frame. A multi-frame BVH is an animation, and
/// silently taking its first frame would turn a wrong file into a plausible
/// wrong pose.
/// One frame of a BVH, as a pose.
///
/// The counterpart of `loadBodyPose` for a file that IS an animation. Naming a
/// frame is the caller saying they know it is one, which is what lets
/// `loadBodyPose` keep refusing multi-frame files outright: the danger it
/// guards against is a walk cycle silently becoming "the pose", and a caller
/// who wrote `7` has not done that by accident.
///
/// It is what made the shipped animations reachable at all. Measured,
/// `data/animations/zombie/zombieWalk1.bvh` holds 31 frames and
/// `walks/walk1.bvh` holds 14, and before this every one of them was refused.
///
/// @param frame zero-based. Out of range is an error naming the real count,
///        because a user who guessed needs to know what to guess instead.
/// How many of @p skeleton's bones @p path actually drives.
///
/// `makePoseUnits` matches a BVH joint to a bone by IDENTICAL NAME and leaves
/// every unmatched bone at identity, so a file naming nothing the rig knows
/// produces the rest pose in silence. That is not hypothetical: the shipped
/// `data/animations/` walks name 75 joints of the OLD MakeHuman skeleton
/// (`Spine1`, `Clavicle_L`) and match **0** of this port's 163, which
/// `tests/unit/test_pose_frame.cpp` pins. Counting the matches is what lets a
/// caller say so instead of posing nothing and reporting success.
///
/// Counted by NAME rather than by inspecting the resulting transforms: a
/// neutral frame is legitimately near-identity -- `face-poseunits.bvh` frame 0
/// carries 373 non-zero channels of about 1e-6 -- so "every bone is identity"
/// cannot tell "drove nothing" from "drove a neutral pose".
///
/// Reads @p path, so call it once per pose rather than per frame.
///
/// @param names an optional table renaming the file's joints before the match
///        (`retargetJoints`). nullptr is the old behaviour -- the file's own
///        names, matched literally.
[[nodiscard]] std::expected<size_t, PoseUnitsError> bonesDrivenBy(
    const std::filesystem::path& path, const Skeleton& skeleton,
    const RetargetMap* names = nullptr);

[[nodiscard]] std::expected<std::vector<Mat4>, PoseUnitsError> loadBodyPoseFrame(
    const std::filesystem::path& path, const Skeleton& skeleton, size_t frame,
    const RetargetMap* names = nullptr);

/// Per-bone rotations aligning THIS rig's rest to the source file's rest.
///
/// **This is what makes a retargeted animation land where its author put it.**
/// A BVH's rotations are deltas from the file's OWN rest, and the shipped
/// `data/animations/*.bvh` rest in a T-pose while this rig rests in an A-pose.
/// Applying the delta from the wrong rest leaves every bone off by the angle
/// between the two rests -- MEASURED on walk1 before this existed:
/// `upperarm01` 42.3 degrees out, `lowerarm01` 53.6, `wrist` 78.4, which is
/// what folded the forearms up across the chest. The error is CONSTANT rather
/// than per-frame, because one rotation applied to two directions preserves
/// the angle between them, so one constant rotation per bone closes it.
///
/// Two rules earn their place, and both were found by rendering:
///
/// 1. A **branching** source joint is skipped. `Hips` carries the spine and
///    both legs and has no single segment below it; taking one put `hips`
///    150.7 degrees out and tore the pelvis open.
/// 2. The comparison spans the **same anatomy** in both skeletons -- this
///    bone's head to the head of the bone the source's child joint names --
///    not "this bone's own direction". This rig splits the neck into three
///    and interposes `upperarm02` in the humerus where the file has one bone
///    each, so a bone-for-bone comparison measured a third of our neck
///    against the whole of theirs and put `neck01` 22.2 degrees out.
///
/// An UNDRIVEN bone inherits its parent's rotation rather than taking
/// identity: a bone that kept its own rest while its parent was re-oriented
/// would refuse to follow the parent, tearing the mesh at exactly the joints
/// this port has just finished untearing.
///
/// The twist about a bone's axis is underdetermined by two directions, and
/// this takes the rotation that adds none -- the only defensible choice, since
/// a BVH joint carries no roll to copy.
///
/// Exposed so it can be gated directly: the tear gate cannot see this, because
/// removing the correction leaves the mesh whole and merely WRONG.
///
/// @param bvh joints ALREADY renamed through the retarget map, so a joint and
///        the bone it drives share a name.
/// @return one rotation per bone of @p skeleton, parents before children.
[[nodiscard]] std::vector<Mat4> restAlignment(const io::BvhFile& bvh, const Skeleton& skeleton);

[[nodiscard]] std::expected<std::vector<Mat4>, PoseUnitsError> loadBodyPose(
    const std::filesystem::path& path, const Skeleton& skeleton,
    const RetargetMap* names = nullptr);

/// Layers @p overlay's transforms for @p bones onto @p base, leaving the rest
/// of @p base alone. This is what puts a facial expression on a posed body.
///
/// The reference (`shared/animation.py:449-467`) copies pose1 and assigns
/// pose2's rows for the listed indices; it raises when the two poses have
/// different bone counts, because mixing poses built for different skeletons
/// produces a plausible-looking wrong body. Both refusals are kept:
///
///   - differing sizes -> `FrameCountMismatch`;
///   - a bone index past the end -> `Malformed` (the reference would raise
///     IndexError; silently skipping it would drop part of the expression).
///
/// Order does not matter here and no interpolation happens -- unlike
/// PoseUnits::blend, this replaces rather than composes.
[[nodiscard]] std::expected<std::vector<Mat4>, PoseUnitsError> mixPoses(
    std::span<const Mat4> base, std::span<const Mat4> overlay, std::span<const size_t> bones);

}  // namespace mh::rig
