// SPDX-License-Identifier: AGPL-3.0-or-later
//
// A real saved model, loaded and applied: .mhm -> modifiers -> geometry,
// compared against what the reference produces from the same file.
//
// The .mhm files and their reference geometry are generated by driving the
// reference's own Human.save() and Human.load() headlessly.

#include "makehuman/core/Mhm.h"

#include "makehuman/core/Modifier.h"
#include "makehuman/core/ObjReader.h"
#include "makehuman/core/TargetIndex.h"

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <limits>
#include <vector>

using Catch::Matchers::WithinAbs;
using namespace mh::core;

namespace {

std::filesystem::path mhmDir() {
    return std::filesystem::path(MH_GOLDEN_DIR) / "mhm";
}

std::vector<float> readBlob(const std::filesystem::path& p) {
    std::ifstream in(p, std::ios::binary | std::ios::ate);
    if (!in) return {};
    const auto bytes = static_cast<size_t>(in.tellg());
    in.seekg(0);
    std::vector<float> out(bytes / sizeof(float));
    in.read(reinterpret_cast<char*>(out.data()), static_cast<std::streamsize>(bytes));
    return out;
}

std::vector<Modifier> loadAllModifiers() {
    std::vector<Modifier> all;
    for (const char* f :
         {"modeling_modifiers.json", "measurement_modifiers.json", "bodyshapes_modifiers.json"}) {
        auto m = loadModifiers(std::filesystem::path(MH_DATA_DIR) / "modifiers" / f);
        if (m) all.insert(all.end(), m->begin(), m->end());
    }
    return all;
}

}  // namespace

TEST_CASE("a .mhm file parses into its parts", "[core][mhm]") {
    const auto path = mhmDir() / "mixed.mhm";
    if (!std::filesystem::exists(path)) SKIP("mhm fixture not present");

    const auto m = loadMhm(path);
    REQUIRE(m.has_value());

    CHECK(m->version == "v1.3.0");
    CHECK(m->name == "mixed");
    CHECK(m->hasCamera);
    CHECK_THAT(m->camera[0], WithinAbs(12.0, 1e-4));
    CHECK_THAT(m->camera[5], WithinAbs(1.5, 1e-4));

    // Every macro modifier is written even at its default, plus any non-zero
    // slider (human.py:1611-1613).
    CHECK(m->modifiers.size() >= 11);

    bool foundGender = false;
    bool foundHead   = false;
    for (const auto& [name, value] : m->modifiers) {
        if (name == "macrodetails/Gender") {
            foundGender = true;
            CHECK_THAT(value, WithinAbs(1.0, 1e-5));
        }
        if (name == "head/head-age-decr|incr") {
            foundHead = true;
            CHECK_THAT(value, WithinAbs(0.5, 1e-5));
        }
    }
    CHECK(foundGender);
    CHECK(foundHead);
}

TEST_CASE("version comparison uses major and minor only", "[core][mhm]") {
    // human.py:1461-1466 matches with the regex v(\d)\.(\d), so the patch
    // component is deliberately ignored.
    MhmFile m;
    m.version = "v1.3.0";
    CHECK(m.versionMatches("v1.3.0"));
    CHECK(m.versionMatches("v1.3.7"));
    CHECK_FALSE(m.versionMatches("v1.2.0"));
    CHECK_FALSE(m.versionMatches("v2.3.0"));
    CHECK_FALSE(m.versionMatches("nonsense"));
}

TEST_CASE("unrecognised lines are preserved rather than dropped", "[core][mhm]") {
    // skeleton / pose / proxy / material lines come from plugins this build
    // does not have yet; losing them would corrupt a round trip.
    const auto path = mhmDir() / "mixed.mhm";
    if (!std::filesystem::exists(path)) SKIP("mhm fixture not present");

    const auto m = loadMhm(path);
    REQUIRE(m.has_value());
    for (const std::string& line : m->unhandled) {
        INFO(line);
        CHECK_FALSE(line.starts_with("modifier "));
        CHECK_FALSE(line.starts_with("version "));
    }
}

TEST_CASE("a missing file is reported", "[core][mhm]") {
    const auto m = loadMhm("/definitely/not/here.mhm");
    REQUIRE_FALSE(m.has_value());
    CHECK(m.error().kind == MhmErrorKind::NotFound);
    CHECK_FALSE(m.error().message().empty());
}

TEST_CASE("loading a .mhm reproduces the reference's geometry", "[golden][parity][fixture][mhm]") {
    const auto idx = TargetIndex::build(MH_DATA_DIR);
    if (idx.componentCount() == 0) SKIP("target data not present");
    const auto mods = loadAllModifiers();
    REQUIRE_FALSE(mods.empty());

    auto baseMesh = loadObj(std::filesystem::path(MH_DATA_DIR) / "3dobjs" / "base.obj");
    REQUIRE(baseMesh.has_value());
    TargetLibrary targets(MH_DATA_DIR);

    for (const char* name : {"neutral", "mixed"}) {
        const auto mhmPath   = mhmDir() / (std::string(name) + ".mhm");
        const auto coordPath = mhmDir() / (std::string(name) + ".coord.bin");
        if (!std::filesystem::exists(mhmPath) || !std::filesystem::exists(coordPath)) {
            SKIP("mhm fixture not present");
        }
        INFO("model: " << name);

        const auto mhm = loadMhm(mhmPath);
        REQUIRE(mhm.has_value());

        Human h(&idx, mods);
        uint32_t unknown       = 0;
        const uint32_t applied = applyMhm(*mhm, h, &unknown);
        CHECK(applied == mhm->modifiers.size());
        CHECK(unknown == 0);

        uint32_t missing = 0;
        h.applyStack(*baseMesh, targets, &missing);
        CHECK(missing == 0);

        const auto expected = readBlob(coordPath);
        REQUIRE(expected.size() == baseMesh->vertexCount() * 3);

        size_t bad  = 0;
        float worst = 0.0F;
        for (size_t i = 0; i < baseMesh->vertexCount(); ++i) {
            const Vec3& got = baseMesh->coord()[i];
            const float d   = std::max({std::abs(got.x - expected[i * 3 + 0]),
                                        std::abs(got.y - expected[i * 3 + 1]),
                                        std::abs(got.z - expected[i * 3 + 2])});
            worst           = std::max(worst, d);
            if (d > 1e-5F) ++bad;
        }
        INFO("worst delta " << worst);
        CHECK(bad == 0);
    }
}

// --- the writer -------------------------------------------------------------

TEST_CASE("a .mhm written by us is byte-identical to the reference's", "[mhm][golden][parity]") {
    // reference_save.mhm IS the reference's own Human.save() output -- captured
    // by `capture_fixture.py mhm_save`, with a uuid, mixed-case duplicate tags,
    // a camera and two plugin-contributed lines, none of which the other two
    // fixtures carry. (neutral/mixed were committed without a generator, so
    // their provenance is NOT verifiable; they stay as round-trip corpus, not
    // as evidence about the reference.)
    //
    // Byte equality here is parity with the format itself: field order, the
    // six-decimal modifier values, the sorted lower-cased tags, plugin lines
    // before `subdivide`, and the trailing newline SaveWriter adds
    // (human.py:1619-1623).
    for (const char* name : {"reference_save.mhm", "neutral.mhm", "mixed.mhm"}) {
        INFO(name);
        const std::filesystem::path source = std::filesystem::path(MH_GOLDEN_DIR) / "mhm" / name;

        const auto loaded = loadMhm(source);
        REQUIRE(loaded.has_value());

        const std::filesystem::path out =
            std::filesystem::temp_directory_path() / (std::string("mh-roundtrip-") + name);
        REQUIRE(saveMhm(out, *loaded).has_value());

        const auto read = [](const std::filesystem::path& p) {
            std::ifstream in(p, std::ios::binary);
            REQUIRE(in);
            return std::string(std::istreambuf_iterator<char>(in),
                               std::istreambuf_iterator<char>());
        };
        CHECK(read(out) == read(source));
        std::filesystem::remove(out);
    }
}

TEST_CASE("a saved file loads back with the same values", "[mhm]") {
    const auto loaded = loadMhm(std::filesystem::path(MH_GOLDEN_DIR) / "mhm" / "mixed.mhm");
    REQUIRE(loaded.has_value());

    const std::filesystem::path out = std::filesystem::temp_directory_path() / "mh-reload.mhm";
    REQUIRE(saveMhm(out, *loaded).has_value());

    const auto again = loadMhm(out);
    REQUIRE(again.has_value());
    std::filesystem::remove(out);

    CHECK(again->version == loaded->version);
    CHECK(again->name == loaded->name);
    CHECK(again->writtenBy == loaded->writtenBy);
    CHECK(again->subdivide == loaded->subdivide);
    CHECK(again->hasCamera == loaded->hasCamera);
    REQUIRE(again->modifiers.size() == loaded->modifiers.size());
    for (size_t i = 0; i < again->modifiers.size(); ++i) {
        INFO("modifier " << i << " " << loaded->modifiers[i].first);
        // Order is part of the format, so this compares positionally.
        CHECK(again->modifiers[i].first == loaded->modifiers[i].first);
        CHECK_THAT(static_cast<double>(again->modifiers[i].second),
                   WithinAbs(static_cast<double>(loaded->modifiers[i].second), 1e-6));
    }
}

TEST_CASE("saving to an unwritable path is reported, not silently lost", "[mhm]") {
    MhmFile m;
    m.version    = "v1.3.0";
    const auto r = saveMhm("/definitely/not/a/directory/x.mhm", m);
    REQUIRE_FALSE(r.has_value());
    CHECK(r.error().kind == MhmErrorKind::Unreadable);
}

TEST_CASE("mhmFromHuman writes every macro but only non-zero shape sliders", "[mhm]") {
    const TargetIndex idx = TargetIndex::build(std::filesystem::path(MH_DATA_DIR) / "targets");
    auto mods =
        loadModifiers(std::filesystem::path(MH_DATA_DIR) / "modifiers" / "modeling_modifiers.json");
    REQUIRE(mods.has_value());
    const size_t macroCount =
        static_cast<size_t>(std::count_if(mods->begin(), mods->end(), [](const Modifier& m) {
            return m.kind == ModifierKind::Macro || m.kind == ModifierKind::Ethnic;
        }));
    REQUIRE(macroCount > 0);

    Human h(&idx, *mods);
    const MhmFile fresh = mhmFromHuman(h, "fresh");
    // Untouched: only the macros, because a macro's default is 0.5 and leaving
    // it out would load back as 0.
    CHECK(fresh.modifiers.size() == macroCount);
    CHECK(fresh.name == "fresh");

    REQUIRE(h.setModifierValue("head/head-oval", 0.4F));
    const MhmFile withShape = mhmFromHuman(h, "shaped");
    CHECK(withShape.modifiers.size() == macroCount + 1);

    // Back to zero and it drops out again.
    REQUIRE(h.setModifierValue("head/head-oval", 0.0F));
    CHECK(mhmFromHuman(h, "x").modifiers.size() == macroCount);
}

TEST_CASE("tags are lower-cased, truncated and de-duplicated on load", "[mhm]") {
    // human.py:131, reached from the loader at :1524-1526. The reference stores
    // them in a set and sorts on write, so "Zulu;alpha;MIKE;alpha" comes back
    // as "alpha;mike;zulu" -- not the raw strings in file order.
    const auto loaded =
        loadMhm(std::filesystem::path(MH_GOLDEN_DIR) / "mhm" / "reference_save.mhm");
    REQUIRE(loaded.has_value());

    std::vector<std::string> tags = loaded->tags;
    std::sort(tags.begin(), tags.end());
    CHECK(tags == std::vector<std::string>{"alpha", "mike", "zulu"});

    // The rest of the reference's own header survived the parse.
    CHECK(loaded->uuid == "1234-abcd");
    CHECK(loaded->name == "hero");
    CHECK(loaded->hasCamera);
    // Plugin lines this build has no handler for are kept verbatim.
    CHECK(loaded->unhandled ==
          std::vector<std::string>{"skeleton default.mhskel", "material Braid01 mhmat"});
}

TEST_CASE("camera keeps the precision the format carries", "[mhm]") {
    // Python writes camera values with '%s', up to 17 significant digits. Held
    // as float they came back as -13.4 and 1.1 -- a different file.
    const std::filesystem::path out = std::filesystem::temp_directory_path() / "mh-camera.mhm";
    {
        std::ofstream f(out, std::ios::binary);
        REQUIRE(f);
        f << "version v1.3.0\n"
          << "camera -13.399999999999999 27.200000000000003 0.0 0.0 0.0 1.0999999999999999\n"
          << "subdivide False\n";
    }
    const auto loaded = loadMhm(out);
    REQUIRE(loaded.has_value());
    REQUIRE(loaded->hasCamera);

    const std::filesystem::path back =
        std::filesystem::temp_directory_path() / "mh-camera-back.mhm";
    REQUIRE(saveMhm(back, *loaded).has_value());

    std::ifstream in(back);
    REQUIRE(in);
    std::string line;
    bool found = false;
    while (std::getline(in, line)) {
        if (!line.starts_with("camera ")) continue;
        found = true;
        CHECK(line ==
              "camera -13.399999999999999 27.200000000000003 0.0 0.0 0.0 1.0999999999999999");
    }
    CHECK(found);
    std::filesystem::remove(out);
    std::filesystem::remove(back);
}

TEST_CASE("loading a second character must reset first, or the two blend", "[mhm]") {
    // The reference resets before applying (human.py:1486 -> resetMeshValues,
    // :1293-1305). applyMhm deliberately does NOT -- it is the apply step, and
    // its name says so -- which makes the reset the caller's job and this the
    // test that says why.
    const TargetIndex idx = TargetIndex::build(std::filesystem::path(MH_DATA_DIR) / "targets");
    auto mods =
        loadModifiers(std::filesystem::path(MH_DATA_DIR) / "modifiers" / "modeling_modifiers.json");
    REQUIRE(mods.has_value());

    const auto neutral = loadMhm(std::filesystem::path(MH_GOLDEN_DIR) / "mhm" / "neutral.mhm");
    REQUIRE(neutral.has_value());
    // The file must not mention this modifier, or the test proves nothing.
    REQUIRE(std::none_of(neutral->modifiers.begin(), neutral->modifiers.end(),
                         [](const auto& kv) { return kv.first == "head/head-oval"; }));

    Human blended(&idx, *mods);
    REQUIRE(blended.setModifierValue("head/head-oval", 0.4F));
    applyMhm(*neutral, blended, nullptr);
    // Without a reset the previous character's head survives the load.
    CHECK_THAT(static_cast<double>(blended.modifierValue("head/head-oval")), WithinAbs(0.4, 1e-6));

    Human clean(&idx, *mods);
    REQUIRE(clean.setModifierValue("head/head-oval", 0.4F));
    clean.resetToDefaults();
    applyMhm(*neutral, clean, nullptr);
    CHECK_THAT(static_cast<double>(clean.modifierValue("head/head-oval")), WithinAbs(0.0, 1e-6));

    // And the reset does not throw away what the file DOES set.
    CHECK_THAT(static_cast<double>(clean.modifierValue("macrodetails/Gender")),
               WithinAbs(0.5, 1e-6));
}

TEST_CASE("the camera mapping round-trips and anchors on the reference's default", "[mhm]") {
    // The format stores a magnification (lib/camera.py:454-457: 0.25..15,
    // default 1.0); this renderer orbits at a distance. The mapping is anchored
    // so the default view writes the default zoom.
    const OrbitView defaultView{0.0F, 0.0F, kDefaultOrbitDistance};
    const auto packed = mhmCameraFrom(defaultView);
    CHECK_THAT(packed[5], WithinAbs(1.0, 1e-9));
    // An unpanned view still writes zero translation.
    CHECK_THAT(packed[2], WithinAbs(0.0, 1e-12));
    CHECK_THAT(packed[3], WithinAbs(0.0, 1e-12));
    CHECK_THAT(packed[4], WithinAbs(0.0, 1e-12));

    // Closer is a bigger magnification, which is the direction that makes the
    // sign of the relationship checkable rather than assumed.
    CHECK(mhmCameraFrom({0.0F, 0.0F, 22.5F})[5] > 1.0);
    CHECK(mhmCameraFrom({0.0F, 0.0F, 90.0F})[5] < 1.0);

    for (const OrbitView& view :
         {OrbitView{0.0F, 0.0F, kDefaultOrbitDistance}, OrbitView{-30.0F, 125.0F, 12.0F},
          OrbitView{89.0F, -359.0F, 300.0F},
          OrbitView{10.0F, 20.0F, 30.0F, {0.25F, -0.5F, 0.75F}}}) {
        INFO("pitch " << view.pitchDegrees << " yaw " << view.yawDegrees << " distance "
                      << view.distance);
        const OrbitView back = orbitFromMhmCamera(mhmCameraFrom(view));
        CHECK_THAT(static_cast<double>(back.pitchDegrees),
                   WithinAbs(static_cast<double>(view.pitchDegrees), 1e-4));
        CHECK_THAT(static_cast<double>(back.yawDegrees),
                   WithinAbs(static_cast<double>(view.yawDegrees), 1e-4));
        CHECK_THAT(static_cast<double>(back.distance),
                   WithinAbs(static_cast<double>(view.distance), 1e-3));
        for (size_t i = 0; i < 3; ++i) {
            CHECK_THAT(static_cast<double>(back.translation[i]),
                       WithinAbs(static_cast<double>(view.translation[i]), 1e-6));
        }
    }
}

// --- Camera pan -------------------------------------------------------------
//
// The format's camera line holds a TRANSLATION in slots 2..4 that this port
// wrote as zeros and read as nothing, so panning a loaded character and saving
// it silently discarded the pan.
//
// The units are the reference's, not ours: `lib/camera.py:544-546` multiplies
// the stored translation by the human's half-extents, so the value on disk is a
// FRACTION of the model's size, clamped to [-1, 1] (`camera.py:608-610`).
// Storing world decimetres here would write a file MakeHuman 1.x reads as a pan
// of many body-widths.
TEST_CASE("the camera translation survives a round trip, in the format's units", "[mhm]") {
    const OrbitView panned{0.0F, 0.0F, kDefaultOrbitDistance, {0.5F, -0.25F, 0.125F}};
    const auto packed = mhmCameraFrom(panned);
    CHECK_THAT(packed[2], WithinAbs(0.5, 1e-9));
    CHECK_THAT(packed[3], WithinAbs(-0.25, 1e-9));
    CHECK_THAT(packed[4], WithinAbs(0.125, 1e-9));

    const OrbitView back = orbitFromMhmCamera(packed);
    CHECK_THAT(static_cast<double>(back.translation[0]), WithinAbs(0.5, 1e-6));
    CHECK_THAT(static_cast<double>(back.translation[1]), WithinAbs(-0.25, 1e-6));
    CHECK_THAT(static_cast<double>(back.translation[2]), WithinAbs(0.125, 1e-6));
}

TEST_CASE("an out-of-range translation is clamped, not written raw", "[mhm]") {
    // `camera.py:608-610` clamps to [-1, 1] on every pan. A file holding 40
    // would otherwise put the model forty body-widths off screen with no way
    // back, in this viewer and in MakeHuman 1.x alike.
    const auto packed = mhmCameraFrom({0.0F, 0.0F, kDefaultOrbitDistance, {40.0F, -40.0F, 0.0F}});
    CHECK_THAT(packed[2], WithinAbs(1.0, 1e-9));
    CHECK_THAT(packed[3], WithinAbs(-1.0, 1e-9));

    const OrbitView back = orbitFromMhmCamera({0.0, 0.0, 40.0, -40.0, 0.0, 1.0});
    CHECK(back.translation[0] == 1.0F);
    CHECK(back.translation[1] == -1.0F);

    // And a non-finite one falls back to zero rather than poisoning the view,
    // the same rule the rotations already follow.
    const OrbitView bad =
        orbitFromMhmCamera({0.0, 0.0, std::numeric_limits<double>::infinity(), 1e300, 0.0, 1.0});
    CHECK(bad.translation[0] == 0.0F);
    CHECK(bad.translation[1] == 0.0F);
}

TEST_CASE("pitch and yaw go in the slots the format uses", "[mhm]") {
    // The round trip above is self-inverse under a consistent swap of fields 0
    // and 1, so it cannot tell pitch from yaw. human.py:1607 writes
    // getRotation()[:2], and lib/camera.py:603 returns
    // [verticalInclination, horizontalRotation, 0] -- pitch first.
    const auto pitchOnly = mhmCameraFrom({7.0F, 0.0F, kDefaultOrbitDistance});
    CHECK_THAT(pitchOnly[0], WithinAbs(7.0, 1e-5));
    CHECK_THAT(pitchOnly[1], WithinAbs(0.0, 1e-9));

    const auto yawOnly = mhmCameraFrom({0.0F, 7.0F, kDefaultOrbitDistance});
    CHECK_THAT(yawOnly[0], WithinAbs(0.0, 1e-9));
    CHECK_THAT(yawOnly[1], WithinAbs(7.0, 1e-5));
}

TEST_CASE("a camera the format allows but a float cannot hold is refused", "[mhm]") {
    // parseFloat rejects nan and inf, but 1e300 is a perfectly finite double
    // and a legal camera rotation as far as the parser is concerned. Narrowed
    // to float it becomes inf, and saveMhm's ".0" fixup then writes `inf.0`,
    // which neither this loader nor MakeHuman 1.x can read.
    const OrbitView huge = orbitFromMhmCamera({1e300, -1e300, 0, 0, 0, 1.0});
    CHECK(std::isfinite(huge.pitchDegrees));
    CHECK(std::isfinite(huge.yawDegrees));
    CHECK_THAT(static_cast<double>(huge.pitchDegrees), WithinAbs(0.0, 1e-9));

    // And nothing non-finite can escape into a file.
    for (const double d : mhmCameraFrom(huge))
        CHECK(std::isfinite(d));
    for (const double d : mhmCameraFrom({std::numeric_limits<float>::infinity(), 0.0F, 10.0F})) {
        CHECK(std::isfinite(d));
    }
}

TEST_CASE("a zoom too small to divide by is refused, not turned into infinity", "[mhm]") {
    // The guard used to test only `zoom > 0`, but 45.0 / 1e-38 overflows float
    // long before it divides by zero -- and an infinite orbit distance renders
    // an empty viewport with nothing reported.
    for (const double zoom : {1e-38, 1e-320, 1e-45}) {
        INFO("zoom " << zoom);
        const OrbitView view = orbitFromMhmCamera({0, 0, 0, 0, 0, zoom});
        CHECK(std::isfinite(view.distance));
        CHECK_THAT(static_cast<double>(view.distance),
                   WithinAbs(static_cast<double>(kDefaultOrbitDistance), 1e-4));
    }
}

TEST_CASE("a zero or absent zoom falls back rather than dividing by zero", "[mhm]") {
    // A hand-edited or truncated file must not produce an infinite distance and
    // a viewport showing nothing.
    CHECK_THAT(static_cast<double>(orbitFromMhmCamera({0, 0, 0, 0, 0, 0.0}).distance),
               WithinAbs(static_cast<double>(kDefaultOrbitDistance), 1e-6));
    CHECK_THAT(static_cast<double>(orbitFromMhmCamera({0, 0, 0, 0, 0, -2.0}).distance),
               WithinAbs(static_cast<double>(kDefaultOrbitDistance), 1e-6));
    // A distance of zero on the way out would divide by zero too.
    CHECK_THAT(mhmCameraFrom({0.0F, 0.0F, 0.0F})[5], WithinAbs(1.0, 1e-9));
}
