// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Parity of modifier construction against the Python reference: every
// modifier's full name, range, kind and per-side target group names.
//
// tests/golden/modifiers.txt is generated by constructing the reference's own
// UniversalModifier / MacroModifier / EthnicModifier objects from the same
// JSON, using its class-selection logic (humanmodifier.py:677-696).

#include "makehuman/core/Modifier.h"

#include <catch2/catch_test_macros.hpp>

#include <cmath>

#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using namespace mh::core;

namespace {

struct Row {
    std::string fullName, kind, left, right, center;
    float minV{}, maxV{};
};

std::map<std::string, Row> loadExpected() {
    std::map<std::string, Row> out;
    std::ifstream in(std::filesystem::path(MH_GOLDEN_DIR) / "modifiers.txt");
    std::string line;
    while (std::getline(in, line)) {
        std::stringstream ss(line);
        std::vector<std::string> f;
        std::string cell;
        while (std::getline(ss, cell, '\t'))
            f.push_back(cell);
        while (f.size() < 7)
            f.emplace_back();
        if (f[0].empty()) continue;
        Row r;
        r.fullName      = f[0];
        r.minV          = std::strtof(f[1].c_str(), nullptr);
        r.maxV          = std::strtof(f[2].c_str(), nullptr);
        r.kind          = f[3];
        r.left          = f[4];
        r.right         = f[5];
        r.center        = f[6];
        out[r.fullName] = std::move(r);
    }
    return out;
}

std::vector<Modifier> loadAll() {
    std::vector<Modifier> all;
    for (const char* f :
         {"modeling_modifiers.json", "measurement_modifiers.json", "bodyshapes_modifiers.json"}) {
        auto m = loadModifiers(std::filesystem::path(MH_DATA_DIR) / "modifiers" / f);
        if (m) all.insert(all.end(), m->begin(), m->end());
    }
    return all;
}

}  // namespace

TEST_CASE("every modifier matches the Python reference", "[golden][parity][modifier]") {
    const auto expected = loadExpected();
    if (expected.empty()) SKIP("modifiers.txt not present");

    const auto all = loadAll();
    if (all.empty()) SKIP("modifier data not present");

    // Measured from the reference: 291 modifiers across the three shipped files.
    CHECK(expected.size() == 291);
    CHECK(all.size() == expected.size());

    std::map<std::string, const Modifier*> byName;
    for (const Modifier& m : all)
        byName[m.fullName] = &m;

    size_t missing = 0, wrongRange = 0, wrongSides = 0, wrongKind = 0;
    for (const auto& [name, want] : expected) {
        const auto it = byName.find(name);
        if (it == byName.end()) {
            ++missing;
            UNSCOPED_INFO("missing modifier: " << name);
            continue;
        }
        const Modifier& got = *it->second;

        if (got.minValue() != want.minV || got.maxValue() != want.maxV) {
            ++wrongRange;
            UNSCOPED_INFO(name << ": range [" << got.minValue() << "," << got.maxValue()
                               << "] want [" << want.minV << "," << want.maxV << "]");
        }
        if (got.left != want.left || got.right != want.right || got.center != want.center) {
            ++wrongSides;
            UNSCOPED_INFO(name << ": sides L='" << got.left << "' R='" << got.right << "' C='"
                               << got.center << "' want L='" << want.left << "' R='" << want.right
                               << "' C='" << want.center << "'");
        }
        const bool wantUniversal = want.kind == "UniversalModifier";
        const bool wantEthnic    = want.kind == "EthnicModifier";
        const bool kindOk        = wantUniversal ? (got.kind == ModifierKind::Universal)
                                   : wantEthnic  ? (got.kind == ModifierKind::Ethnic)
                                                 : (got.kind == ModifierKind::Macro);
        if (!kindOk) {
            ++wrongKind;
            UNSCOPED_INFO(name << ": kind mismatch, want " << want.kind);
        }
    }

    CHECK(missing == 0);
    CHECK(wrongRange == 0);
    CHECK(wrongSides == 0);
    CHECK(wrongKind == 0);

    size_t extra = 0;
    for (const Modifier& m : all) {
        if (!expected.contains(m.fullName)) {
            ++extra;
            UNSCOPED_INFO("unexpected modifier: " << m.fullName);
        }
    }
    CHECK(extra == 0);
}

TEST_CASE("the default character's target stack is small and correct",
          "[golden][parity][modifier]") {
    const auto idx = TargetIndex::build(MH_DATA_DIR);
    if (idx.componentCount() == 0) SKIP("target data not present");
    const auto all = loadAll();
    if (all.empty()) SKIP("modifier data not present");

    const Human h(&idx, all);

    // At defaults every Universal slider is 0, so only the macro groups
    // contribute: 6 from macrodetails and 2 from macrodetails-universal.
    // height, proportions and breast all contribute nothing (no
    // average* files for the first two; the all-average breast combination
    // does not exist). See the note in test_target_index_parity.cpp.
    CHECK(h.stackSize() == 8);

    float total = 0.0F;
    for (const auto& [path, w] : h.stack()) {
        INFO(path << " = " << w);
        CHECK(w > 0.0F);  // zero weights must never be stored
        total += w;
    }
    CHECK(std::abs(total - 2.0F) < 1e-4F);  // 1.0 from each contributing group
}

TEST_CASE("moving a macro slider re-weights the stack", "[golden][parity][modifier]") {
    const auto idx = TargetIndex::build(MH_DATA_DIR);
    if (idx.componentCount() == 0) SKIP("target data not present");
    const auto all = loadAll();
    if (all.empty()) SKIP("modifier data not present");

    Human h(&idx, all);
    REQUIRE(h.setModifierValue("macrodetails/Gender", 1.0F));

    // Fully male: the female half of each macro pair drops out entirely.
    for (const auto& [path, w] : h.stack()) {
        INFO(path);
        CHECK(path.find("female") == std::string::npos);
    }
    CHECK(h.stackSize() == 3 + 1);  // 3 races x male x young, plus universal
}

TEST_CASE("a universal slider adds exactly one side", "[golden][parity][modifier]") {
    const auto idx = TargetIndex::build(MH_DATA_DIR);
    if (idx.componentCount() == 0) SKIP("target data not present");
    const auto all = loadAll();
    if (all.empty()) SKIP("modifier data not present");

    Human h(&idx, all);
    const size_t before = h.stackSize();

    // A bipolar slider: positive value engages the max side only.
    REQUIRE(h.setModifierValue("head/head-age-decr|incr", 1.0F));
    CHECK(h.stackSize() == before + 1);

    bool foundIncr = false;
    for (const auto& [path, w] : h.stack()) {
        if (path.find("head-age-incr") != std::string::npos) {
            foundIncr = true;
            CHECK(std::abs(w - 1.0F) < 1e-5F);
        }
        CHECK(path.find("head-age-decr") == std::string::npos);
    }
    CHECK(foundIncr);

    // Negative engages the min side instead.
    REQUIRE(h.setModifierValue("head/head-age-decr|incr", -1.0F));
    bool foundDecr = false;
    for (const auto& [path, w] : h.stack()) {
        if (path.find("head-age-decr") != std::string::npos) foundDecr = true;
        CHECK(path.find("head-age-incr") == std::string::npos);
    }
    CHECK(foundDecr);

    // Back to zero: the slider leaves no trace.
    REQUIRE(h.setModifierValue("head/head-age-decr|incr", 0.0F));
    CHECK(h.stackSize() == before);
}
