// SPDX-License-Identifier: AGPL-3.0-or-later
//
// A real saved model, loaded and applied: .mhm -> modifiers -> geometry,
// compared against what the reference produces from the same file.
//
// The .mhm files and their reference geometry are generated by driving the
// reference's own Human.save() and Human.load() headlessly.

#include "makehuman/core/Mhm.h"

#include "makehuman/core/Modifier.h"
#include "makehuman/core/ObjReader.h"

#include <catch2/catch_test_macros.hpp>
#include <catch2/matchers/catch_matchers_floating_point.hpp>

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <vector>

using Catch::Matchers::WithinAbs;
using namespace mh::core;

namespace {

std::filesystem::path mhmDir() {
    return std::filesystem::path(MH_GOLDEN_DIR) / "mhm";
}

std::vector<float> readBlob(const std::filesystem::path& p) {
    std::ifstream in(p, std::ios::binary | std::ios::ate);
    if (!in) return {};
    const auto bytes = static_cast<size_t>(in.tellg());
    in.seekg(0);
    std::vector<float> out(bytes / sizeof(float));
    in.read(reinterpret_cast<char*>(out.data()), static_cast<std::streamsize>(bytes));
    return out;
}

std::vector<Modifier> loadAllModifiers() {
    std::vector<Modifier> all;
    for (const char* f :
         {"modeling_modifiers.json", "measurement_modifiers.json", "bodyshapes_modifiers.json"}) {
        auto m = loadModifiers(std::filesystem::path(MH_DATA_DIR) / "modifiers" / f);
        if (m) all.insert(all.end(), m->begin(), m->end());
    }
    return all;
}

}  // namespace

TEST_CASE("a .mhm file parses into its parts", "[core][mhm]") {
    const auto path = mhmDir() / "mixed.mhm";
    if (!std::filesystem::exists(path)) SKIP("mhm fixture not present");

    const auto m = loadMhm(path);
    REQUIRE(m.has_value());

    CHECK(m->version == "v1.3.0");
    CHECK(m->name == "mixed");
    CHECK(m->hasCamera);
    CHECK_THAT(m->camera[0], WithinAbs(12.0, 1e-4));
    CHECK_THAT(m->camera[5], WithinAbs(1.5, 1e-4));

    // Every macro modifier is written even at its default, plus any non-zero
    // slider (human.py:1611-1613).
    CHECK(m->modifiers.size() >= 11);

    bool foundGender = false;
    bool foundHead   = false;
    for (const auto& [name, value] : m->modifiers) {
        if (name == "macrodetails/Gender") {
            foundGender = true;
            CHECK_THAT(value, WithinAbs(1.0, 1e-5));
        }
        if (name == "head/head-age-decr|incr") {
            foundHead = true;
            CHECK_THAT(value, WithinAbs(0.5, 1e-5));
        }
    }
    CHECK(foundGender);
    CHECK(foundHead);
}

TEST_CASE("version comparison uses major and minor only", "[core][mhm]") {
    // human.py:1461-1466 matches with the regex v(\d)\.(\d), so the patch
    // component is deliberately ignored.
    MhmFile m;
    m.version = "v1.3.0";
    CHECK(m.versionMatches("v1.3.0"));
    CHECK(m.versionMatches("v1.3.7"));
    CHECK_FALSE(m.versionMatches("v1.2.0"));
    CHECK_FALSE(m.versionMatches("v2.3.0"));
    CHECK_FALSE(m.versionMatches("nonsense"));
}

TEST_CASE("unrecognised lines are preserved rather than dropped", "[core][mhm]") {
    // skeleton / pose / proxy / material lines come from plugins this build
    // does not have yet; losing them would corrupt a round trip.
    const auto path = mhmDir() / "mixed.mhm";
    if (!std::filesystem::exists(path)) SKIP("mhm fixture not present");

    const auto m = loadMhm(path);
    REQUIRE(m.has_value());
    for (const std::string& line : m->unhandled) {
        INFO(line);
        CHECK_FALSE(line.starts_with("modifier "));
        CHECK_FALSE(line.starts_with("version "));
    }
}

TEST_CASE("a missing file is reported", "[core][mhm]") {
    const auto m = loadMhm("/definitely/not/here.mhm");
    REQUIRE_FALSE(m.has_value());
    CHECK(m.error().kind == MhmErrorKind::NotFound);
    CHECK_FALSE(m.error().message().empty());
}

TEST_CASE("loading a .mhm reproduces the reference's geometry", "[golden][parity][fixture][mhm]") {
    const auto idx = TargetIndex::build(MH_DATA_DIR);
    if (idx.componentCount() == 0) SKIP("target data not present");
    const auto mods = loadAllModifiers();
    REQUIRE_FALSE(mods.empty());

    auto baseMesh = loadObj(std::filesystem::path(MH_DATA_DIR) / "3dobjs" / "base.obj");
    REQUIRE(baseMesh.has_value());
    TargetLibrary targets(MH_DATA_DIR);

    for (const char* name : {"neutral", "mixed"}) {
        const auto mhmPath   = mhmDir() / (std::string(name) + ".mhm");
        const auto coordPath = mhmDir() / (std::string(name) + ".coord.bin");
        if (!std::filesystem::exists(mhmPath) || !std::filesystem::exists(coordPath)) {
            SKIP("mhm fixture not present");
        }
        INFO("model: " << name);

        const auto mhm = loadMhm(mhmPath);
        REQUIRE(mhm.has_value());

        Human h(&idx, mods);
        uint32_t unknown       = 0;
        const uint32_t applied = applyMhm(*mhm, h, &unknown);
        CHECK(applied == mhm->modifiers.size());
        CHECK(unknown == 0);

        uint32_t missing = 0;
        h.applyStack(*baseMesh, targets, &missing);
        CHECK(missing == 0);

        const auto expected = readBlob(coordPath);
        REQUIRE(expected.size() == baseMesh->vertexCount() * 3);

        size_t bad  = 0;
        float worst = 0.0F;
        for (size_t i = 0; i < baseMesh->vertexCount(); ++i) {
            const Vec3& got = baseMesh->coord()[i];
            const float d   = std::max({std::abs(got.x - expected[i * 3 + 0]),
                                        std::abs(got.y - expected[i * 3 + 1]),
                                        std::abs(got.z - expected[i * 3 + 2])});
            worst           = std::max(worst, d);
            if (d > 1e-5F) ++bad;
        }
        INFO("worst delta " << worst);
        CHECK(bad == 0);
    }
}
