#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate the Mixamo-compatible superset skeleton.

    python3 tools/build_mixamo_superset.py           # write it
    python3 tools/build_mixamo_superset.py --check   # fail if the file is stale

Takes `data/rigs/default.mhskel` (163 bones) and adds the 16 bones Mixamo needs
that MakeHuman lacks, producing `data/rigs/mixamo_superset.mhskel` (179). Every
MakeHuman bone survives; every Mixamo bone has a home. See
`docs/rig/mixamo_mapping.md` for why this is a superset rather than a swap.

Generated rather than hand-edited, so `tools/mixamo_mapping.py` stays the single
source of truth for what maps to what: changing the mapping and re-running this
cannot leave the two disagreeing.

**No new joint vertex-groups are needed.** Every added bone reuses a joint that
already exists -- a fingertip is the tail of the last phalanx, `hips` sits on
`root`'s tail, and so on -- so the superset introduces no new dependency on the
base mesh's helper geometry.
"""

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SOURCE = REPO / "data" / "rigs" / "default.mhskel"
OUTPUT = REPO / "data" / "rigs" / "mixamo_superset.mhskel"
SOURCE_WEIGHTS = REPO / "data" / "rigs" / "default_weights.mhw"
OUTPUT_WEIGHTS = REPO / "data" / "rigs" / "mixamo_superset_weights.mhw"
BASE_MESH = REPO / "data" / "3dobjs" / "base.obj"

# name -> (parent, head joint, tail joint). Ordered so a parent always precedes
# its children, which loadSkeleton() requires.
#
# `hips` is the one that matters: Mixamo's Hips pivot is where the legs and the
# spine meet, which is `root`'s TAIL, not its head -- 0.92 dm apart. Binding it
# to `root` would swing the whole character about a point ~9 cm behind the
# sacrum on every rotation and every root-motion translation.
ADDED: list[tuple[str, str, str, str]] = [
    ("hips", "root", "root____tail", "spine05____tail"),
    ("HeadTop_End", "head", "head____tail", "head____tail"),
]
for _side, _sfx in (("Left", ".L"), ("Right", ".R")):
    # The ball of the foot: one bone parenting every toe, which MakeHuman has no
    # equivalent for -- all five toes hang straight off `foot`, so there is no
    # way to express a foot roll. This is the one addition that is a real,
    # weight-bearing joint rather than a tip marker.
    ADDED.append((f"ball{_sfx}", f"foot{_sfx}", f"foot{_sfx}____tail", f"toe3-1{_sfx}____head"))
    ADDED.append((f"toe_end{_sfx}", f"ball{_sfx}", f"toe1-2{_sfx}____tail",
                  f"toe1-2{_sfx}____tail"))
    for _finger in range(1, 6):
        ADDED.append((f"finger{_finger}-4{_sfx}", f"finger{_finger}-3{_sfx}",
                      f"finger{_finger}-3{_sfx}____tail", f"finger{_finger}-3{_sfx}____tail"))

# The toes move under `ball`, which is what makes a foot roll possible at all.
REPARENT: dict[str, str] = {"pelvis.L": "hips", "pelvis.R": "hips", "spine05": "hips"}
for _sfx in (".L", ".R"):
    for _toe in range(1, 6):
        REPARENT[f"toe{_toe}-1{_sfx}"] = f"ball{_sfx}"


def _add_bones(bones: dict, joints: dict) -> None:
    for name, parent, head, tail in ADDED:
        if name in bones:
            raise SystemExit(f"{name} already exists in {SOURCE.name}")
        for ref in (head, tail):
            if ref not in joints:
                raise SystemExit(f"{name} wants joint {ref}, which does not exist")
        bones[name] = {"head": head, "parent": parent, "reference": None,
                       "rotation_plane": None, "tail": tail}


def _reparent(bones: dict) -> None:
    for child, parent in REPARENT.items():
        if child not in bones:
            raise SystemExit(f"cannot reparent {child}: no such bone")
        bones[child] = dict(bones[child], parent=parent)


def _parents_first(bones: dict) -> dict[str, dict]:
    """loadSkeleton() requires every parent to precede its child."""
    ordered: dict[str, dict] = {}

    def emit(name: str) -> None:
        if name in ordered:
            return
        parent = bones[name].get("parent")
        if parent:
            emit(parent)
        ordered[name] = bones[name]

    for name in bones:
        emit(name)
    return ordered


def build() -> dict:
    skeleton = json.loads(SOURCE.read_text())
    bones = dict(skeleton["bones"])

    _add_bones(bones, skeleton["joints"])
    _reparent(bones)

    skeleton["bones"] = _parents_first(bones)
    skeleton["name"] = "Mixamo superset"
    skeleton["description"] = (
        "MakeHuman's default rig plus the 16 bones Mixamo names and it lacks. "
        "Every MakeHuman bone survives; every Mixamo bone has a home. "
        "Generated by tools/build_mixamo_superset.py -- do not hand-edit.")
    return skeleton


def mesh_coords() -> list[tuple[float, float, float]]:
    out = []
    for line in BASE_MESH.read_text().splitlines():
        if line.startswith("v "):
            _, x, y, z = line.split()[:4]
            out.append((float(x), float(y), float(z)))
    return out


def joint_position(skeleton: dict, ref: str,
                   coords: list[tuple[float, float, float]]) -> tuple[float, float, float]:
    idx = skeleton["joints"][ref]
    return tuple(sum(coords[i][k] for i in idx) / len(idx) for k in range(3))


def build_weights(skeleton: dict) -> dict:
    """Hand `ball` its share of the foot's forward vertices.

    Rotating `ball` already moves the toes -- they are its children and carry
    their own weights -- so a foot roll works without this. What it does not do
    is deform the *crease at the ball of the foot*, because that skin still
    belongs entirely to `foot`. This gives `ball` that skin.

    The rule is a linear ramp between the ball joint and the toe roots: a vertex
    at the ball line keeps all its `foot` weight, one at the toe roots gives all
    of it to `ball`, and in between it is split. Weight is **moved, never
    created** -- each vertex's total influence is identical before and after,
    which `main` asserts rather than assumes. Nothing outside the foot is
    touched.
    """
    weights = json.loads(SOURCE_WEIGHTS.read_text())
    table = weights["weights"]
    coords = mesh_coords()

    for suffix in (".L", ".R"):
        foot, ball = f"foot{suffix}", f"ball{suffix}"
        if foot not in table:
            raise SystemExit(f"{foot} has no weights to divide")
        start = joint_position(skeleton, skeleton["bones"][ball]["head"], coords)[2]
        end = joint_position(skeleton, skeleton["bones"][ball]["tail"], coords)[2]
        if end <= start:
            raise SystemExit(f"{ball} does not point forward; cannot ramp")

        kept, moved = [], []
        for vertex, weight in table[foot]:
            z = coords[vertex][2]
            share = min(1.0, max(0.0, (z - start) / (end - start)))
            if share > 0.0:
                moved.append([vertex, round(weight * share, 6)])
            if share < 1.0:
                kept.append([vertex, round(weight * (1.0 - share), 6)])
        table[foot] = [[v, w] for v, w in kept if w > 0.0]
        table[ball] = [[v, w] for v, w in moved if w > 0.0]

    weights["name"] = "Mixamo superset weights"
    weights["description"] = (
        "default_weights.mhw with the foot's forward influence divided between "
        "foot and the new ball bone. Generated by tools/build_mixamo_superset.py "
        "-- do not hand-edit.")
    return weights


def total_influence(table: dict) -> dict[int, float]:
    """Total weight on each vertex, across every bone."""
    out: dict[int, float] = {}
    for rows in table.values():
        for vertex, weight in rows:
            out[vertex] = out.get(vertex, 0.0) + weight
    return out


def main() -> int:
    built = build()
    text = json.dumps(built, indent=4, sort_keys=False) + "\n"

    weights = build_weights(built)
    # Weight is redistributed, never created: if any vertex's total influence
    # moved, the skin would deform differently everywhere that vertex appears.
    before = total_influence(json.loads(SOURCE_WEIGHTS.read_text())["weights"])
    after = total_influence(weights["weights"])
    drifted = [v for v in before if abs(before[v] - after.get(v, 0.0)) > 1e-4]
    if drifted:
        raise SystemExit(
            f"{len(drifted)} vertices changed total influence, e.g. {drifted[0]}: "
            f"{before[drifted[0]]:.6f} -> {after.get(drifted[0], 0.0):.6f}")
    weights_text = json.dumps(weights, indent=4, sort_keys=False) + "\n"

    if "--check" in sys.argv:
        if not OUTPUT.exists():
            print(f"{OUTPUT} does not exist; run without --check", file=sys.stderr)
            return 1
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; re-run without --check", file=sys.stderr)
            return 1
        if not OUTPUT_WEIGHTS.exists() or OUTPUT_WEIGHTS.read_text() != weights_text:
            print(f"{OUTPUT_WEIGHTS} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{OUTPUT.name} is up to date ({len(built['bones'])} bones)")
        return 0

    OUTPUT.write_text(text)
    OUTPUT_WEIGHTS.write_text(weights_text)
    print(f"wrote {OUTPUT.relative_to(REPO)} with {len(built['bones'])} bones "
          f"({len(built['bones']) - len(json.loads(SOURCE.read_text())['bones'])} added)")
    for suffix in (".L", ".R"):
        print(f"  ball{suffix}: {len(weights['weights'][f'ball{suffix}'])} vertices, "
              f"foot{suffix} keeps {len(weights['weights'][f'foot{suffix}'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
