#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generate the Mixamo-compatible superset skeleton.

    python3 tools/build_mixamo_superset.py           # write it
    python3 tools/build_mixamo_superset.py --check   # fail if the file is stale

Takes `data/rigs/default.mhskel` (163 bones) and adds the 16 bones Mixamo needs
that MakeHuman lacks, producing `data/rigs/mixamo_superset.mhskel` (179). Every
MakeHuman bone survives; every Mixamo bone has a home. See
`docs/rig/mixamo_mapping.md` for why this is a superset rather than a swap.

Generated rather than hand-edited, so `tools/mixamo_mapping.py` stays the single
source of truth for what maps to what: changing the mapping and re-running this
cannot leave the two disagreeing.

**No new joint vertex-groups are needed.** Every added bone reuses a joint that
already exists -- a fingertip is the tail of the last phalanx, `hips` sits on
`root`'s tail, and so on -- so the superset introduces no new dependency on the
base mesh's helper geometry.
"""

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
SOURCE = REPO / "data" / "rigs" / "default.mhskel"
OUTPUT = REPO / "data" / "rigs" / "mixamo_superset.mhskel"

# name -> (parent, head joint, tail joint). Ordered so a parent always precedes
# its children, which loadSkeleton() requires.
#
# `hips` is the one that matters: Mixamo's Hips pivot is where the legs and the
# spine meet, which is `root`'s TAIL, not its head -- 0.92 dm apart. Binding it
# to `root` would swing the whole character about a point ~9 cm behind the
# sacrum on every rotation and every root-motion translation.
ADDED: list[tuple[str, str, str, str]] = [
    ("hips", "root", "root____tail", "spine05____tail"),
    ("HeadTop_End", "head", "head____tail", "head____tail"),
]
for _side, _sfx in (("Left", ".L"), ("Right", ".R")):
    # The ball of the foot: one bone parenting every toe, which MakeHuman has no
    # equivalent for -- all five toes hang straight off `foot`, so there is no
    # way to express a foot roll. This is the one addition that is a real,
    # weight-bearing joint rather than a tip marker.
    ADDED.append((f"ball{_sfx}", f"foot{_sfx}", f"foot{_sfx}____tail", f"toe3-1{_sfx}____head"))
    ADDED.append((f"toe_end{_sfx}", f"ball{_sfx}", f"toe1-2{_sfx}____tail",
                  f"toe1-2{_sfx}____tail"))
    for _finger in range(1, 6):
        ADDED.append((f"finger{_finger}-4{_sfx}", f"finger{_finger}-3{_sfx}",
                      f"finger{_finger}-3{_sfx}____tail", f"finger{_finger}-3{_sfx}____tail"))

# The toes move under `ball`, which is what makes a foot roll possible at all.
REPARENT: dict[str, str] = {"pelvis.L": "hips", "pelvis.R": "hips", "spine05": "hips"}
for _sfx in (".L", ".R"):
    for _toe in range(1, 6):
        REPARENT[f"toe{_toe}-1{_sfx}"] = f"ball{_sfx}"


def build() -> dict:
    skeleton = json.loads(SOURCE.read_text())
    bones = dict(skeleton["bones"])
    joints = skeleton["joints"]

    for name, parent, head, tail in ADDED:
        if name in bones:
            raise SystemExit(f"{name} already exists in {SOURCE.name}")
        for ref in (head, tail):
            if ref not in joints:
                raise SystemExit(f"{name} wants joint {ref}, which does not exist")
        bones[name] = {"head": head, "parent": parent, "reference": None,
                       "rotation_plane": None, "tail": tail}

    for child, parent in REPARENT.items():
        if child not in bones:
            raise SystemExit(f"cannot reparent {child}: no such bone")
        bones[child] = dict(bones[child], parent=parent)

    # loadSkeleton() requires every parent to precede its child.
    ordered: dict[str, dict] = {}

    def emit(name: str) -> None:
        if name in ordered:
            return
        parent = bones[name].get("parent")
        if parent:
            emit(parent)
        ordered[name] = bones[name]

    for name in bones:
        emit(name)

    skeleton["bones"] = ordered
    skeleton["name"] = "Mixamo superset"
    skeleton["description"] = (
        "MakeHuman's default rig plus the 16 bones Mixamo names and it lacks. "
        "Every MakeHuman bone survives; every Mixamo bone has a home. "
        "Generated by tools/build_mixamo_superset.py -- do not hand-edit.")
    return skeleton


def main() -> int:
    built = build()
    text = json.dumps(built, indent=4, sort_keys=False) + "\n"

    if "--check" in sys.argv:
        if not OUTPUT.exists():
            print(f"{OUTPUT} does not exist; run without --check", file=sys.stderr)
            return 1
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; re-run without --check", file=sys.stderr)
            return 1
        print(f"{OUTPUT.name} is up to date ({len(built['bones'])} bones)")
        return 0

    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT.relative_to(REPO)} with {len(built['bones'])} bones "
          f"({len(built['bones']) - len(json.loads(SOURCE.read_text())['bones'])} added)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
