# SPDX-License-Identifier: AGPL-3.0-or-later
"""Eyelashes grown as individual hairs, from the base mesh's own lash cages.

    MH_APP=<makehuman> ./.venv-mh/bin/python tools/make_eyelash_hairs.py

WHY THIS EXISTS. The shipped eyelashes were the four `helper-*-eyelashes-*`
cages copied verbatim -- 250 vertices, 184 faces -- with a strand texture
painted on them. A cage is a flat SLAB, and rendered at head framing that is
exactly what it read as: grey polygonal wedges above and below the eye with
hard straight edges, running well past the corners. No texture fixes it,
because the geometry has no hairs in it.

That finding is not new here. `make_hair_styles.derive()` records it for the
afro, and the rope styles' skullcap went the same way on the same day. The
eyelashes were the last slab in the tree.

THE CAGE IS STILL THE SOURCE OF TRUTH, which is what keeps this honest: it
already says where the lashes sit, which way they point and how long they are.
Its margin edge is the lash line, and the vector from the margin to the tip
edge is the growth direction at that point. Nothing about the shape is invented
here -- the cage is read and then drawn as hairs instead of as a sheet.
"""

import argparse
import collections
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import coiled_hair as C  # noqa: E402
import make_hair_styles as H  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data" / "eyelashes"
BASE = ROOT / "data" / "3dobjs" / "base.obj"

CAGES = (
    # group, upper?, hairs a side
    ("helper-l-eyelashes-2", True, 120),
    ("helper-r-eyelashes-2", True, 120),
    ("helper-l-eyelashes-1", False, 65),
    ("helper-r-eyelashes-1", False, 65),
)

# A real upper lid carries 90-160 lashes and a lower 70-80, so 120 and 65 are
# inside the anatomy rather than chosen to look right at one framing.
#
# 120 and not 150: at the top of the range, with cards 0.9 mm wide over a 32 mm
# lid, the upper band overlapped about fourfold and read as a drawn LINE rather
# than as lashes -- strong eyeliner, not hair. Coverage is the product of count
# and width and both were high; this lowers one and `HALF_WIDTH` the other.
SEGMENTS = 6

# 0.0036, down from 0.0045. A lash is 0.1 mm across and this is 0.7 mm, for the
# reason the brow records: a ribbon seen near edge-on shows a fraction of its
# width and the alpha sheet eats the rest. Narrower now that the band no longer
# has to carry the density on its own.
HALF_WIDTH = 0.0036

# How far the tip curls away from the straight line the cage gives, as a
# fraction of the lash's length. Upper lashes curl up and out; lower ones are
# nearly straight, which is what separates them at a glance.
CURL_UPPER = 0.30
CURL_LOWER = 0.10

# Roots are drawn INSIDE the lid. A hair emerges from skin; the end of one is
# never visible, and a card whose open edge floats above the surface reads as a
# cut stub -- the fault this tree carried on every style until it was measured.
# 0.014, not 0.004. The cage's margin edge is not quite the lid edge -- it sits
# a little out on the lid -- so lashes grown straight off it left a strip of
# bare skin between the lash line and the eye, which no real eye has. Walking
# the root back along its own growth direction puts the band against the eye
# and buries the card's open edge in the lid at the same time.
ROOT_SINK = 0.014

MATERIAL = "materials/eyelashes.mhmat"

MATERIAL_TEXT = """
# Generated by tools/make_eyelash_hairs.py.
#
# A SINGLE-STRAND sheet, because each card here is ONE LASH. The lashes were a
# sheet until this generator existed -- the base mesh's helper cages -- and six
# strands across that sheet was right for a sheet. A lash card is two columns
# wide in `u`, and six strands across two columns is the aliasing that shredded
# the afro and striped the rope tubes.
#
# `transparent True` is load-bearing: without the flag the renderer discards the
# alpha and paints an opaque rectangle per lash.
#
# Near-black, and darker than the brow: lashes read almost entirely as
# silhouette against the eye white at this scale.
name Eyelashes
tag MakeHuman\u2122
ambientColor 0.02 0.02 0.02
diffuseColor 0.10 0.09 0.08
specularColor 0.3 0.3 0.3
shininess 0.2
opacity 1.0
transparent True
diffuseTexture ../lash_strands.png
backfaceCull False
castShadows True
receiveShadows True
shader data/shaders/glsl/litsphere
"""
# THE BINDER'S SEARCH BOX, and it is TIGHT for a measured reason. The cages
# this replaces bound by IDENTITY -- each vertex named its own helper vertex --
# so nothing but the eyelid could ever move them, and the suite pins that: a
# jaw drop moves the teeth and the whole tongue and leaves the lashes exactly
# where they were.
#
# Cards bind barycentrically instead, to whatever triangle is nearest. With the
# box reaching down to y 6.8 that let lashes catch triangles the jaw drives:
# MEASURED, AU26 moved 379 of 6,020 lash vertices where the cage moved 0.
# Closing the box onto the orbit leaves only eyelid triangles to bind to.
REGION = "-0.70,0.70,7.05,7.55,1.15,1.65"


def read_cages():
    """The four lash cages from the base mesh, as {group: (verts, faces)}."""
    verts, group = [], ""
    faces = collections.defaultdict(list)
    for line in BASE.read_text().splitlines():
        if line.startswith("v "):
            verts.append(tuple(float(t) for t in line.split()[1:4]))
        elif line.startswith("g "):
            group = line.split(None, 1)[1].strip()
        elif line.startswith("f ") and "eyelashes" in group:
            faces[group].append([int(p.split("/")[0]) - 1 for p in line.split()[1:]])
    if len(faces) != 4:
        raise SystemExit(f"expected 4 eyelash cages in the base mesh, found {len(faces)}")
    return verts, faces


def boundary_chains(verts, faces, upper):
    """The cage's margin and tip edges, each ordered along the eye.

    An edge used by exactly one face is on the boundary, and a strip's boundary
    is a single LOOP: along the margin, round one end, back along the tip, round
    the other. So the two chains are found by walking the loop and cutting it at
    the strip's two ends -- the vertices furthest apart along the eye.

    A first version split the loop by whether a vertex sat above or below the
    cage's mid-height instead. MEASURED, that does not give a lid margin: the
    chain it returned spread 0.0406 dm in y, half the cage's entire height, and
    its segments varied 33-fold after sorting, because it swept up the end caps
    and parts of both edges. Resampling that bunched the lashes into a handful
    of clumps with bare lid between them, which is exactly how it rendered.
    """
    used = collections.Counter()
    for f in faces:
        for i in range(len(f)):
            a, b = f[i], f[(i + 1) % len(f)]
            used[(min(a, b), max(a, b))] += 1
    edges = [e for e, n in used.items() if n == 1]
    if not edges:
        raise SystemExit("a lash cage has no boundary")
    nxt = collections.defaultdict(list)
    for a, b in edges:
        nxt[a].append(b)
        nxt[b].append(a)
    start = min(nxt, key=lambda i: verts[i][0])
    loop, seen = [start], {start}
    while True:
        step = [v for v in nxt[loop[-1]] if v not in seen]
        if not step:
            break
        loop.append(step[0])
        seen.add(step[0])
    if len(loop) != len(nxt):
        raise SystemExit(f"a lash cage's boundary is not one loop "
                         f"({len(loop)} of {len(nxt)} walked)")
    # The two ends of the strip: furthest apart along the eye.
    i0 = min(range(len(loop)), key=lambda k: verts[loop[k]][0])
    i1 = max(range(len(loop)), key=lambda k: verts[loop[k]][0])
    lo, hi = sorted((i0, i1))
    one = loop[lo:hi + 1]
    two = loop[hi:] + loop[:lo + 1]
    # The MARGIN is the edge against the eye: the low side of an upper cage and
    # the high side of a lower one.
    def height(chain):
        return sum(verts[i][1] for i in chain) / len(chain)

    margin, tip = (one, two) if (height(one) < height(two)) == upper else (two, one)
    margin = sorted(margin, key=lambda i: verts[i][0])
    tip = sorted(tip, key=lambda i: verts[i][0])
    return margin, tip


def resample(points, count):
    """`count` points spread evenly by arc length along a polyline."""
    if len(points) < 2:
        return list(points) * count
    seg = [C.length(C.sub(b, a)) for a, b in zip(points, points[1:])]
    total = sum(seg)
    if total <= 0.0:
        return list(points[:1]) * count
    out, walked, k = [], 0.0, 0
    for n in range(count):
        want = total * (n + 0.5) / count
        while k < len(seg) - 1 and walked + seg[k] < want:
            walked += seg[k]
            k += 1
        f = 0.0 if seg[k] <= 0.0 else (want - walked) / seg[k]
        out.append(tuple(points[k][j] + (points[k + 1][j] - points[k][j]) * f
                         for j in range(3)))
    return out


def lash(root, grow, curl, rng_phase):
    """One lash: out along the cage's own direction, curling as it goes.

    The curl is a quadratic lift perpendicular to the growth direction, so the
    hair leaves the lid straight -- which is what a lash does, it is stiff at
    the root -- and bends only toward the tip.
    """
    up = (0.0, 1.0, 0.0)
    side = C.cross(grow, up)
    if C.length(side) < 1e-6:
        side = (1.0, 0.0, 0.0)
    bend = C.normalise(C.cross(side, grow), up)
    span = C.length(grow)
    pts = []
    for i in range(SEGMENTS + 1):
        s = i / SEGMENTS
        # Quadratic: zero slope at the root, all of the bend at the tip.
        lift = curl * span * s * s
        # A little per-lash variation so neighbours do not lie in one plane.
        # 0.035, not the 0.12 this started at: the phase steps by the golden
        # angle, so at 0.12 of the span adjacent lashes diverged hard and the
        # upper lid rendered as splayed clumps with gaps between them instead of
        # a line. The variation is meant to stop the lashes looking stamped, not
        # to fan them apart.
        wobble = 0.035 * span * math.sin(rng_phase) * s
        p = C.add(root, C.scale(grow, s))
        p = C.add(p, C.scale(bend, lift))
        pts.append(C.add(p, C.scale(side, wobble)))
    return pts


def ribbon(points, half_width, face_dir):
    """A lash widened into a card that faces `face_dir`."""
    pts, uvs, quads = [], [], []
    n = len(points) - 1
    for i, p in enumerate(points):
        nxt = points[min(i + 1, n)]
        prv = points[max(i - 1, 0)]
        tangent = C.normalise(C.sub(nxt, prv), (0.0, 1.0, 0.0))
        across = C.cross(tangent, face_dir)
        if C.length(across) < 1e-6:
            across = C.cross(tangent, (1.0, 0.0, 0.0))
        across = C.normalise(across, (1.0, 0.0, 0.0))
        t = i / n
        # Tapering to a point: a card that stops square reads as a stick, which
        # is the note the eyebrow generator carries for the same reason.
        w = half_width * (1.0 - 0.80 * t)
        pts.append(C.sub(p, C.scale(across, w)))
        pts.append(C.add(p, C.scale(across, w)))
        uvs.append((0.0, t))
        uvs.append((1.0, t))
    for i in range(n):
        a, b = 2 * i, 2 * i + 1
        quads.append([a, b, b + 2, a + 2])
    return pts, quads, uvs


def build():
    verts, cages = read_cages()
    allpts, allquads, alluvs = [], [], []
    counts = {}
    for group, upper, hairs in CAGES:
        faces = cages[group]
        margin_i, tip_i = boundary_chains(verts, faces, upper)
        margin = [verts[i] for i in margin_i]
        tip = [verts[i] for i in tip_i]
        roots = resample(margin, hairs)
        # The cage's own direction and length at each root: the nearest point on
        # the tip edge. Nothing here is invented -- the cage says where the
        # lashes point and the resampled tip edge says how far.
        tips = resample(tip, hairs)
        curl = CURL_UPPER if upper else CURL_LOWER
        for n, (r, t) in enumerate(zip(roots, tips)):
            grow = C.sub(t, r)
            if C.length(grow) < 1e-6:
                continue
            # SINK THE ROOT into the lid, opposite the growth direction.
            r = C.add(r, C.scale(C.normalise(grow), -ROOT_SINK))
            strand = lash(r, C.sub(t, r), curl, n * 2.399963)
            # The card faces along the eye, so a lash seen head-on still shows
            # its width rather than its edge.
            pts, quads, uvs = ribbon(strand, HALF_WIDTH, (0.0, 0.0, 1.0))
            base = len(allpts)
            allpts.extend(pts)
            alluvs.extend(uvs)
            allquads.extend([[i + base for i in q] for q in quads])
        counts[group] = hairs
    return allpts, allquads, alluvs, counts


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--app", default="", help="the makehuman binary to bind with")
    ap.add_argument("--check", action="store_true",
                    help="report staleness instead of writing")
    args = ap.parse_args()

    pts, quads, uvs, counts = build()
    print(f"eyelashes: {len(pts)} vertices, {len(quads)} faces, "
          f"{sum(counts.values())} hairs, {SEGMENTS} segments each")

    app = args.app or H.app_binary()
    binds = H.bind_points(app, pts, REGION)
    if len(binds) != len(pts):
        raise SystemExit(f"{len(binds)} bindings for {len(pts)} lash points")
    obj, mhclo = H.write_bound_style("Eyelashes", "eyelashes", pts, quads, binds, uvs,
                                     material=MATERIAL,
                                     uuid_override="9d4f60b8-13ac-4e27-b5f1-08e7c62a3d95")
    # THE MATERIAL IS WRITTEN HERE TOO, because this tool now owns the asset.
    # It used to be stamped "Generated by tools/make_helper_proxies.py", and
    # that stopped being true the moment the lashes stopped being cages -- a
    # banner naming a tool that no longer touches the file sends the next person
    # to refresh it with the wrong generator.
    mhmat = MATERIAL_TEXT.lstrip("\n")
    wanted = {"eyelashes.obj": obj, "eyelashes.mhclo": mhclo,
              "materials/eyelashes.mhmat": mhmat}
    stale = [n for n, text in wanted.items()
             if not (OUT / n).exists() or (OUT / n).read_text() != text]
    if args.check:
        for n in stale:
            print(f"{n} differs from a fresh derivation", file=sys.stderr)
        print(f"eyelashes: {len(wanted) - len(stale)} shipped files match a fresh run")
        return 1 if stale else 0
    for n, text in wanted.items():
        (OUT / n).parent.mkdir(parents=True, exist_ok=True)
        (OUT / n).write_text(text)
    print(f"eyelashes: wrote {', '.join(sorted(wanted))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
