#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generates textured-Black hair styles as proxies fitted to the body scalp.

Asked for by the owner: afro (the owner's word is `bambucha`), and later locs,
cornrows and bantu knots. ATTEMPTED 2026-09-11 and not shipped -- five
iterations produced silhouettes too crude to carry the names. `memory/todo.md`
records why, and every number below is measured rather than guessed.

WHAT WENT WRONG LAST TIME, and what is different now:

* Placement raycast from the head centre onto the scalp. The scalp is not a
  closed dome, so a direction grid misses, and the nearest-direction fallback
  silently piled every miss onto the rim. THIS generator never searches for a
  scalp point: it starts from the scalp VERTICES themselves and pushes them
  outward, so there is nothing to miss.
* `helper-hair` was the obvious source and is the wrong one -- it is a long-hair
  envelope carrying ribbons down over the face. The region here is the BODY
  group only.

THE FIT. `fitProxy` (src/core/Proxy.cpp:423-441) computes
    P = SUM w_k * H[v_k] + (m.x*d.x, m.y*d.y, m.z*d.z)
and `TMatrix::diagonal` (src/core/Proxy.cpp:82-84) returns (1,1,1) when the
file declares no scale or shear form -- which this one does not. So `d` is a
plain WORLD-SPACE offset in rest, and a proxy vertex is written as
    <b> <b> <b> 1 0 0 <dx> <dy> <dz>
binding to base vertex b. Rest space is right: fitting runs before skinning
(main.cpp wornSkins), so hair anchored to the scalp follows a head turn free.
"""
import argparse
import collections
import math
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "data" / "3dobjs" / "base.obj"
OUT = ROOT / "data" / "hair"
# Everything this writes lands in `data/hair`, which IS the shipped asset tree:
# `AssetIndex::build` scans it, so a style written there is a wearable the moment
# it exists, and the asset-index test counts it. That is why the generator ships
# only styles that have been rendered and looked at -- an unfinished one dropped
# here once turned that test red on a working copy that had merely RUN this.

BANNER = "# Generated by tools/make_hair_styles.py -- do not edit by hand."

# The cranium centre, measured and recorded in `memory/todo.md`.
CENTRE = (0.0, 7.75, 0.50)

# The hairline, in degrees of elevation about CENTRE, as a function of azimuth
# measured from the FRONT (+z). Measured on the base mesh: forehead sits at
# ~+9 degrees in this frame, brow -13, ears -25, nape -50. An earlier attempt
# used `14 + 20*cos(theta)` in a frame 0.2 dm too low and put every style in a
# band across the crown that read as a headband.
def hairline(azim_deg: float) -> float:
    return -19.0 + 31.0 * math.cos(math.radians(azim_deg))


def read_base():
    verts, faces = [], []
    group = ""
    for line in BASE.read_text().splitlines():
        if line.startswith("v "):
            verts.append(tuple(float(t) for t in line.split()[1:4]))
        elif line.startswith("g "):
            group = line.split(None, 1)[1].strip()
        elif line.startswith("f ") and group == "body":
            faces.append([int(p.split("/")[0]) - 1 for p in line.split()[1:]])
    return verts, faces


def spherical(v):
    """Elevation and azimuth of a vertex about CENTRE, in degrees."""
    dx, dy, dz = v[0] - CENTRE[0], v[1] - CENTRE[1], v[2] - CENTRE[2]
    return (math.degrees(math.atan2(dy, math.hypot(dx, dz))),
            math.degrees(math.atan2(dx, dz)))


def afro(verts, faces, thickness=0.78, edge_deg=20.0, skirt_deg=12.0):
    """A rounded shell standing off the scalp: the afro silhouette.

    Every hair-bearing vertex is pushed out along its own surface NORMAL by
    `thickness`, so the shell is a uniform-depth copy of the skull. An earlier
    version grew each vertex RADIALLY from the cranium centre and rendering it
    settled the matter: radial growth only yields a ball if the source is
    already a sphere, and the scalp is not -- low vertices sit far from the
    centre horizontally, so they pushed sideways and the result was a
    wide-brimmed mushroom cap. A normal offset follows the head, which from the
    front reads as the round halo an afro actually is.

    The offset holds FULL volume across the scalp and eases off only in the
    last `edge_deg` degrees before the hairline, so the shell meets the skin
    tangentially at the edge without losing body anywhere else. MEASURED: a
    single mesh edge changes the hairline margin by a median of 7.2 degrees
    (p90 14.4), so a band narrower than that collapses the whole taper into one
    face -- rendering it at 9 degrees produced dark jagged spikes fanning
    around the face. 30 degrees spans about four rows of vertices. A first version
    eased over the whole scalp -- `margin/deepest` -- and rendering it settled
    the matter: mean offset 0.086 dm, 18 px of added height, no added width,
    and it read as a flat-top sitting too far back with a bare forehead. Volume
    has to be near-constant or it is not an afro.
    """
    margin = {}
    for i, v in enumerate(verts):
        elev, azim = spherical(v)
        m = elev - hairline(azim)
        # A SKIRT of vertices below the hairline is kept in the patch with zero
        # growth. Without it the shell's rim IS the region boundary, and that
        # boundary is a ragged polyline of whichever vertices happened to fall
        # inside -- which rendered as serrations along the hairline. With it the
        # grown part ends inside the patch and the rim lies flat on the skin.
        if m > -skirt_deg:
            margin[i] = m
    if not margin:
        return [], [], {}

    # Only whole faces, and only the vertices those faces use: `loadObj`
    # REJECTS a vertex referenced by no face (src/core/ObjReader.cpp:235-243),
    # and the whole proxy then fails to load -- which renders as a bald head
    # rather than as an error any gate would catch.
    keep = [f for f in faces if all(v in margin for v in f)]
    used = sorted({v for f in keep for v in f})

    # Area-weighted vertex normals over the kept patch, flipped outward: the
    # base mesh's winding is not assumed, it is CHECKED against the direction
    # away from the cranium centre.
    normal = {b: [0.0, 0.0, 0.0] for b in used}
    for f in keep:
        a, bb, c = verts[f[0]], verts[f[1]], verts[f[2]]
        u = (bb[0] - a[0], bb[1] - a[1], bb[2] - a[2])
        w = (c[0] - a[0], c[1] - a[1], c[2] - a[2])
        n = (u[1] * w[2] - u[2] * w[1], u[2] * w[0] - u[0] * w[2], u[0] * w[1] - u[1] * w[0])
        for v in f:
            for k in range(3):
                normal[v][k] += n[k]

    placed = {}
    for b in used:
        n = normal[b]
        ln = math.sqrt(sum(t * t for t in n))
        x, y, z = verts[b]
        out = (x - CENTRE[0], y - CENTRE[1], z - CENTRE[2])
        if ln < 1e-9:
            placed[b] = (0.0, 0.0, 0.0)
            continue
        n = [t / ln for t in n]
        if sum(n[k] * out[k] for k in range(3)) < 0.0:
            n = [-t for t in n]
        # smoothstep over a NARROW band at the hairline only.
        t = min(1.0, max(0.0, margin[b]) / edge_deg)
        ease = t * t * (3.0 - 2.0 * t)
        grow = thickness * ease
        placed[b] = (n[0] * grow, n[1] * grow, n[2] * grow)
    return used, keep, placed


def write_style(name, stem, used, keep, placed, verts):
    index = {b: i for i, b in enumerate(used)}
    obj = [BANNER,
           f"# {name}: {len(used)} vertices, {len(keep)} faces.", "g " + stem]
    pos = []
    for b in used:
        x, y, z = verts[b]
        d = placed[b]
        pos.append((x + d[0], y + d[1], z + d[2]))
        obj.append("v {:.6f} {:.6f} {:.6f}".format(*pos[-1]))
    # CROWN-RADIAL, because a strand texture needs to know which way the hair
    # GROWS and a planar projection cannot say.
    #
    # This used to project x/z over the cap's extent, which is a reasonable
    # unwrap for a skullcap and the wrong one for hair: it makes `u`
    # left-to-right and `v` front-to-back, so a texture whose strands run along
    # `v` draws them from the face to the nape, and a tip fade at v=1 eats the
    # back of the head. RENDERED and looked at, that is exactly what happened --
    # the crown went bald and the rest hung in strings.
    #
    # Hair leaves a scalp from the whorl and travels outward and down, so `v`
    # is the angle away from straight up about the cranium centre, normalised
    # over the cap's own reach, and `u` is the azimuth around it. Strands then
    # run root-to-tip the way they grow, and the tip fade lands on the hem
    # where the silhouette wants breaking up.
    #
    # `u` IS THE AZIMUTH AND THEREFORE WRAPS, which is why the strand texture
    # wraps its own distance calculation: without that there is a seam down the
    # back where u=0.999 meets u=0.001.
    cap = []
    for q in pos:
        dx, dy, dz = q[0] - CENTRE[0], q[1] - CENTRE[1], q[2] - CENTRE[2]
        radial = math.hypot(dx, dz)
        # Angle from +y. atan2 rather than acos(dy/len): it stays well
        # conditioned at the crown, where radial goes to zero.
        cap.append((math.degrees(math.atan2(radial, dy)), math.atan2(dx, dz)))
    reach = max((c[0] for c in cap), default=1.0) or 1.0
    for polar, azim in cap:
        # +0.5 PUTS THE SEAM AT THE NAPE. `atan2(dx, dz)` wraps at azimuth 0,
        # which is the FRONT midline, and a triangle that straddles the wrap has
        # `u` interpolated the long way round -- the whole texture smeared
        # across it. RENDERED, that was a ragged vertical strip down the centre
        # of the forehead, which I first misread as the polar singularity at the
        # crown and tried to cover with a wider root band; widening it changed
        # nothing, because the strip was never at the pole.
        #
        # The smear does not go away by moving it, it goes behind the head.
        # Removing it needs the seam vertices DUPLICATED so each copy carries
        # its own `u`, and this writer emits one `vt` per vertex.
        u = (azim / (2.0 * math.pi) + 0.5) % 1.0
        v = min(1.0, polar / reach)
        obj.append(f"vt {u:.6f} {v:.6f}")
    for f in keep:
        obj.append("f " + " ".join(f"{index[v] + 1}/{index[v] + 1}" for v in f))

    mhclo = [
        BANNER,
        "#",
        "# A shell standing off the BODY scalp. Each vertex binds to the base",
        "# vertex it grew from, with a world-space offset: the fit declares no",
        "# scale form, so TMatrix::diagonal is (1,1,1) and the offset applies",
        "# unchanged (src/core/Proxy.cpp:82-84, 423-441).",
        f"name {name}",
        f"uuid 8f2c1d4a-hair-{stem}",
        "basemesh hm08",
        f"obj_file {stem}.obj",
        "material materials/hair.mhmat",
        "z_depth 60",
        "verts 0",
    ]
    for b in used:
        d = placed[b]
        mhclo.append(f"{b} {b} {b} 1.00000 0.00000 0.00000 "
                     f"{d[0]:.5f} {d[1]:.5f} {d[2]:.5f}")
    return "\n".join(obj) + "\n", "\n".join(mhclo) + "\n"


def write_bound_style(name, stem, points, faces, bindings, uvs=None):
    """A style whose geometry is AUTHORED, not cut from the base mesh.

    The .obj carries the authored positions and the .mhclo carries one binding
    per vertex, in the same order -- which is the contract `fitProxy` reads.
    """
    obj = [BANNER,
           f"# {name}: {len(points)} vertices, {len(faces)} faces.", "g " + stem]
    for x, y, z in points:
        obj.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    # UVs, WITHOUT WHICH A STRAND TEXTURE HAS NOWHERE TO GO. The four generated
    # styles shipped with no `vt` at all, so `materials/hair.mhmat`'s own note
    # -- "needs an alpha-cut strand texture, which the cage geometry cannot
    # stand in for" -- described a thing that could not be wired up even if the
    # texture existed. MEASURED on the export: body 14,517 distinct UVs, eyes
    # 808, teeth 136, hair ZERO.
    #
    # One `vt` per vertex, in vertex order, so a face corner is `v/vt` with the
    # same index twice. That is what the sweeps produce -- u around the tube, v
    # along it -- and it keeps the .obj readable beside the .mhclo, whose
    # bindings are also one per vertex in the same order.
    if uvs and len(uvs) == len(points):
        for u, v in uvs:
            obj.append(f"vt {u:.6f} {v:.6f}")
        for f in faces:
            obj.append("f " + " ".join(f"{i + 1}/{i + 1}" for i in f))
    else:
        if uvs:
            print(f"{stem}: {len(uvs)} uvs for {len(points)} vertices -- writing none",
                  file=sys.stderr)
        for f in faces:
            obj.append("f " + " ".join(str(i + 1) for i in f))
    mhclo = [
        BANNER,
        "#",
        "# AUTHORED geometry bound to the body scalp by three base vertices,",
        "# barycentric weights and an offset -- `mh::core::bindToSurface` via",
        "# `--bind-points`. The scalp is only ten vertices across, so rows this",
        "# fine cannot be cut from base vertices.",
        f"name {name}",
        # A REAL uuid, unlike the `8f2c1d4a-hair-<stem>` placeholder the shipped
        # afro still carries: `AssetIndex::findByUuid` is how a saved model
        # names its proxy, so a style that ships with a malformed one can never
        # be reloaded. The afro's is left alone deliberately -- changing an
        # asset's identity orphans every .mhm that already references it, and
        # that is a migration, not a generator fix.
        f"uuid {uuid.uuid5(uuid.NAMESPACE_URL, 'makehuman/hair/' + stem)}",
        "basemesh hm08",
        f"obj_file {stem}.obj",
        "material materials/hair.mhmat",
        "z_depth 60",
        "verts 0",
    ]
    mhclo.extend(bindings)
    return "\n".join(obj) + "\n", "\n".join(mhclo) + "\n"


def hairline_matches_app(verts, faces, app_path="") -> int:
    """0 if this generator's hairline is the SAME hairline the application walks.

    `mh::core::hairBearingScalp` holds the formula in C++ now, because a braid
    is routed over the region by `pathOverSurface` before any style exists. Two
    copies of a formula drift silently, and the drift would show as an afro
    whose rim sits where no cornrow can start -- so compare the REGIONS, not the
    constants, and let the application be the authority on its own.
    """
    try:
        app = app_binary(app_path)
        theirs = {int(line.split()[0])
                  for line in subprocess.run([app, "--spread-roots", "999"],
                                             capture_output=True, text=True,
                                             check=True).stdout.splitlines()
                  if line.strip()}
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        # A MISSING or failing application is not a failure of THIS comparison,
        # which is about the hairline formula rather than about the styles.
        # Unreachable from `--check` since cornrows began shipping -- `derive()`
        # hard-fails on a missing application first -- but this is also called
        # from a plain run, where the afro alone is still derivable.
        print(f"hairline: need the built application to compare ({exc}) -- skipped",
              file=sys.stderr)
        return 0
    except (ValueError, IndexError) as exc:
        # Output that is not "index x y z" is a DIFFERENT thing: the application
        # ran and answered something this cannot read. Skipping would let a
        # broken binary read as a pass, and letting the ValueError escape would
        # report it as a crash rather than as a diagnosis.
        print(f"hairline: the application answered something unreadable ({exc})",
              file=sys.stderr)
        return 1
    body = set()
    for f in faces:
        body.update(f)
    ours = {v for v in body
            if spherical(verts[v])[0] >= hairline(spherical(verts[v])[1])}
    if ours != theirs:
        print(f"hairline: this generator selects {len(ours)} scalp vertices, the "
              f"application {len(theirs)}; {len(ours ^ theirs)} differ", file=sys.stderr)
        return 1
    print(f"hairline: {len(ours)} scalp vertices, same set as the application")
    return 0


def derive(verts, faces, app_path=""):
    """Every shipped style, as {filename: text}.

    Cornrows need the application -- it owns the scalp region and the
    barycentric binder -- so this raises rather than returning a short dict if
    it cannot be run. A generator that silently ships fewer styles than it
    claims is exactly the failure `--check` exists to catch.
    """
    used, keep, placed = afro(verts, faces)
    obj, mhclo = write_style("Afro", "afro", used, keep, placed, verts)
    wanted = {"afro.obj": obj, "afro.mhclo": mhclo}

    pts, fs, rows, app, cuvs = cornrows(verts, faces, app_path)
    # `len(binds) == len(pts)` alone is satisfied by 0 == 0. If every row failed
    # to trace, that wrote an EMPTY cornrows.obj into `data/hair`, which
    # `loadObj` rejects -- and a rejected proxy renders as a bald head rather
    # than as an error. So the row count is checked too.
    if rows != CORNROW_ROWS:
        raise RuntimeError(f"{rows} of {CORNROW_ROWS} cornrows traced")
    binds = bind_points(app, pts)
    if not pts or len(binds) != len(pts):
        raise RuntimeError(f"{len(binds)} bindings for {len(pts)} cornrow points")
    cobj, cmhclo = write_bound_style("Cornrows", "cornrows", pts, fs, binds, cuvs)
    wanted["cornrows.obj"] = cobj
    wanted["cornrows.mhclo"] = cmhclo

    bpts, bfs, roots, _, cap_binds, ncap, buvs = bantu(verts, faces, app_path)
    # Only the KNOT points go to the binder; the cap already carries its own
    # bindings, one per base vertex it grew from.
    bbinds = cap_binds + bind_points(app, bpts[ncap:])
    if len(bbinds) != len(bpts):
        raise RuntimeError(f"{len(bbinds)} bindings for {len(bpts)} bantu points")
    bobj, bmhclo = write_bound_style("Bantu knots", "bantu_knots", bpts, bfs, bbinds, buvs)
    wanted["bantu_knots.obj"] = bobj
    wanted["bantu_knots.mhclo"] = bmhclo

    lpts, lfs, lroots, _, lshort, lcap, lncap, luvs = locs(verts, faces, app_path)
    # A rope of two rings is not a loc. The failure this names is real and was
    # MEASURED: before `LOC_SCALP_BOTTOM` existed the crown apex read as a shelf
    # and EVERY rope stopped at ZERO steps. Observed range with the style as it
    # ships is 7..26, so the bar sits between the disaster and the shortest real
    # rope. It was 8 while I was guessing, which is one step below nothing --
    # crossing-stacking then shortened one rope to 7 and tripped it.
    if lshort < 5:
        raise RuntimeError(f"the shortest loc is {lshort} steps")
    # Only the ROPE points go to the binder; the cap already carries its own
    # bindings, one per base vertex it grew from.
    lbinds = lcap + bind_points(app, lpts[lncap:])
    if not lpts or len(lbinds) != len(lpts):
        raise RuntimeError(f"{len(lbinds)} bindings for {len(lpts)} loc points")
    lobj, lmhclo = write_bound_style("Locs", "locs", lpts, lfs, lbinds, luvs)
    wanted["locs.obj"] = lobj
    wanted["locs.mhclo"] = lmhclo

    grown = [math.dist((0, 0, 0), placed[b]) for b in used]
    summary = (f"afro: {len(used)} vertices, {len(keep)} faces\n"
               f"  offset 0 at the hairline .. {max(grown):.4f} dm at the crown, "
               f"mean {sum(grown) / len(grown):.4f}\n"
               f"cornrows: {len(pts)} vertices, {len(fs)} faces\n"
               f"locs: {len(lpts)} vertices, {len(lfs)} faces, {len(lroots)} ropes, "
               f"shortest {lshort} steps\n"
               f"bantu knots: {len(bpts)} vertices, {len(bfs)} faces, "
               f"{len(roots)} roots, closest pair "
               f"{min(math.dist(a, b) for i, a in enumerate(roots) for b in roots[i + 1:]):.4f} dm")
    return wanted, summary


def check(verts, faces, wanted, app_path="") -> int:
    """"Generated" is a claim LICENSING.md makes about these files, and without
    a gate it is an aspiration -- a hand-edit to afro.obj would go unnoticed for
    ever."""
    stale = [n for n, text in wanted.items()
             if not (OUT / n).exists() or (OUT / n).read_text() != text]
    for n in stale:
        print(f"{n} differs from a fresh derivation", file=sys.stderr)
    if stale:
        return 1
    print(f"hair: {len(wanted)} files match a fresh derivation")
    return hairline_matches_app(verts, faces, app_path)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="compare the committed assets against a fresh derivation and "
                         "fail if they differ, instead of writing them")
    ap.add_argument("--app", default="",
                    help="the built application to route and bind with; the caller passes "
                         "its own preset's binary rather than letting this guess")
    args = ap.parse_args()

    verts, faces = read_base()
    try:
        wanted, summary = derive(verts, faces, args.app)
    except (subprocess.CalledProcessError, FileNotFoundError, RuntimeError,
            ValueError, IndexError) as exc:
        # NOT a skip. Cornrows ship from `data/hair`, so a run that cannot
        # derive them cannot confirm them either, and saying so beats a green
        # line that covered half the styles.
        #
        # ValueError/IndexError are in the tuple for the same reason: the region
        # is parsed out of the application's stdout with `int(line.split()[0])`,
        # so one stray warning line would turn a diagnosable failure into a
        # traceback -- a CRASHED test rather than a red one with a reason.
        # `hairline_matches_app` already guarded exactly this; the cornrow path
        # had dropped the guard.
        print(f"cannot derive the hair styles without the application: {exc}", file=sys.stderr)
        return 2

    if args.check:
        return check(verts, faces, wanted, args.app)

    for n, text in wanted.items():
        (OUT / n).write_text(text)
    print(summary)
    return 0





# ---------------------------------------------------------------------------
# Cornrows.
#
# Rows are PATHS over the scalp, not stripes painted on a shell. The base mesh
# cannot carry them as offsets on its own vertices: MEASURED, the hair-bearing
# scalp is 1.504 dm wide with a median edge of 0.1436 dm, about ten vertices
# across, so ridge/gap/ridge allows at most five rows one vertex wide -- a
# corrugated cap. So the geometry is AUTHORED here and bound to the scalp by
# `--bind-points`, which is what the barycentric binder exists for.

import subprocess

APP_ENV = "MH_APP"


def app_binary(override: str = "") -> str:
    """The built application, which owns the scalp walk and the binder.

    Shelling out rather than reimplementing: a second Dijkstra and a second
    barycentric solver in Python would drift from the ones the application
    actually uses, and the drift would show as hair that sits right in the
    generator and wrong in the app.
    """
    import os
    # Passed down from `main(--app)` rather than kept in a module global: the
    # global needed a suppression comment to excuse it, and the comment was not
    # even valid suppression syntax (`python:S7632`).
    override = override or os.environ.get(APP_ENV)
    if override:
        return override
    return str(ROOT / "build" / "macos-arm64-debug" / "src" / "app" / "makehuman.app" /
               "Contents" / "MacOS" / "makehuman")


def bind_points(app: str, points, region: str | None = None) -> list[str]:
    """Hand the authored points to the application's barycentric binder.

    The scratch file goes to a TEMPORARY directory, not to `build/`. It used to
    be `ROOT/build/cornrow_points.txt`, which had two faults: `--check` is a
    read-only gate and should not write into the source tree at all, and on a
    checkout never configured in-source `build/` does not exist, so the write
    raised `FileNotFoundError` -- which `main()` then reported as "cannot derive
    the hair styles without the application" while the application was fine.
    """
    import tempfile
    with tempfile.TemporaryDirectory() as d:
        tmp = Path(d) / "points.txt"
        tmp.write_text("".join(f"{x:.6f} {y:.6f} {z:.6f}\n" for x, y, z in points))
        cmd = [app, "--bind-points", str(tmp)]
        # Hair belongs on the scalp and passes nothing; anything that does NOT
        # live on the scalp must say where it does. See `--bind-region`: the
        # offset a binding stores is the distance to the chosen surface, and
        # `fitProxy` scales that offset without rotating it, so binding a brow
        # to the hairline anchors it 38 mm away and it stops following the face.
        if region:
            cmd += ["--bind-region", region]
        out = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout
    return [line for line in out.splitlines() if line.strip()]


# Rows are placed across the crown's width, not the region's; see
# `crown_half_width`. Elevation, in degrees about the cranium centre.
CROWN_ELEVATION = 40.0


def region_triangles(verts, region, body_faces):
    """The region's own triangles, and an outward normal per triangle.

    The filter is per SPLIT TRIANGLE, not per quad, because that is what
    `bindToSurface` does (`src/core/SurfaceBind.cpp:102-112`): it splits first
    and then drops a triangle only if one of ITS three corners is outside the
    region. Filtering per quad was a real difference, not a nicety -- a review
    measured 408 triangles here against the binder's 414, and two of the six
    triangles only the binder saw carry cornrow bindings. Since `max_dist`
    decides where each row ENDS, the rows were being cut against a surface a
    triangle-ring smaller than the one they are actually bound to.
    """
    rs = set(region)
    tris = []
    for f in body_faces:
        for k in range(1, len(f) - 1):
            corners = (f[0], f[k], f[k + 1])
            if not all(v in rs for v in corners):
                continue
            a, b, c = (verts[v] for v in corners)
            u = [b[i] - a[i] for i in range(3)]
            w = [c[i] - a[i] for i in range(3)]
            n = [u[1] * w[2] - u[2] * w[1], u[2] * w[0] - u[0] * w[2],
                 u[0] * w[1] - u[1] * w[0]]
            ln = math.sqrt(sum(t * t for t in n)) or 1.0
            n = [t / ln for t in n]
            mid = [(a[i] + b[i] + c[i]) / 3.0 - CENTRE[i] for i in range(3)]
            if sum(n[i] * mid[i] for i in range(3)) < 0.0:
                n = [-t for t in n]
            tris.append((a, b, c, n))
    return tris


def crown_half_width(verts, region):
    """How far off the midline a row may sit, measured on the crown.

    The region's FULL half-width (0.7521) is the wrong number and using it cost
    two rounds here: it is reached down at ear height, so a row placed there has
    no scalp above it to arc over and the trace finds nothing. MEASURED on the
    shipped mesh, the region narrows with elevation -- 0.6326 above 30 degrees,
    0.5444 above 40, 0.4362 above 50 -- and the widest row has to clear the
    crown, not the temple.
    """
    return max(abs(verts[v][0] - CENTRE[0]) for v in region
               if spherical(verts[v])[0] > CROWN_ELEVATION)


def _along(base, edge, num, den):
    """A point along `edge` from `base`, the degenerate denominator guarded.

    `closestBarycentric` (`src/core/SurfaceBind.cpp:31-74`) guards all four of
    its divisions; the first cut of this port dropped every one. The base mesh
    happens to have no zero-area body triangle today (smallest 5.5e-6), so it
    was latent rather than harmless.

    `if den` rather than `den != 0.0`: an exact float compare trips
    `python:S1244`, and the truthiness form is what the other call sites here
    already use.
    """
    t = num / den if den else 0.0
    return [base[i] + edge[i] * t for i in range(3)]


def _closest_past_ab(p, a, b, c, ab, ac, dots):
    """The half of Ericson's test that needs the third corner's products.

    Split out of `closest_on_triangle` for one reason: together they score 19
    against Sonar's cognitive-complexity limit of 15 (`python:S3776`). The ORDER
    of the tests is deliberately unchanged -- they are Voronoi regions and the
    C++ reference interleaves them exactly this way, so reordering could return
    a different (equally close) point at a tie and silently move the asset.
    """
    d1, d2, d3, d4 = dots
    cp = [p[i] - c[i] for i in range(3)]
    d5 = sum(ab[i] * cp[i] for i in range(3))
    d6 = sum(ac[i] * cp[i] for i in range(3))
    if d6 >= 0.0 and d5 <= d6:
        return c
    vb = d5 * d2 - d1 * d6
    if vb <= 0.0 and d2 >= 0.0 and d6 <= 0.0:
        return _along(a, ac, d2, d2 - d6)
    va = d3 * d6 - d5 * d4
    if va <= 0.0 and (d4 - d3) >= 0.0 and (d5 - d6) >= 0.0:
        bc = [c[i] - b[i] for i in range(3)]
        return _along(b, bc, d4 - d3, (d4 - d3) + (d5 - d6))
    vc = d1 * d4 - d3 * d2
    denom = va + vb + vc
    if not denom:
        return a
    v, w = vb / denom, vc / denom
    return [a[i] + ab[i] * v + ac[i] * w for i in range(3)]


def closest_on_triangle(p, a, b, c):
    """Ericson's closest point on a triangle -- the one `bindToSurface` uses."""
    ab = [b[i] - a[i] for i in range(3)]
    ac = [c[i] - a[i] for i in range(3)]
    ap = [p[i] - a[i] for i in range(3)]
    d1 = sum(ab[i] * ap[i] for i in range(3))
    d2 = sum(ac[i] * ap[i] for i in range(3))
    if d1 <= 0.0 and d2 <= 0.0:
        return a
    bp = [p[i] - b[i] for i in range(3)]
    d3 = sum(ab[i] * bp[i] for i in range(3))
    d4 = sum(ac[i] * bp[i] for i in range(3))
    if d3 >= 0.0 and d4 <= d3:
        return b
    vc = d1 * d4 - d3 * d2
    if vc <= 0.0 and d1 >= 0.0 and d3 <= 0.0:
        return _along(a, ab, d1, d1 - d3)
    return _closest_past_ab(p, a, b, c, ab, ac, (d1, d2, d3, d4))


def project_to_region(p, tris):
    """The closest point on the region, its triangle's normal, and the distance.

    Exhaustive over the region's 408 triangles. An acceleration structure would
    be the third thing here that is faster and wrong: the earlier
    raycast-from-the-centre placement had a nearest-direction FALLBACK that
    silently collapsed every missed ray onto the scalp rim.
    """
    best, bestn, bestd = None, None, float("inf")
    for a, b, c, n in tris:
        q = closest_on_triangle(p, a, b, c)
        d = math.dist(p, q)
        if d < bestd:
            best, bestn, bestd = q, n, d
    return best, bestn, bestd


def trace_row(tris, x, t0=0.0, t1=250.0, samples=70, max_dist=0.04):
    """One row: the scalp's cross-section at x, traced front-to-nape.

    `t` is the angle about the cranium centre in the sagittal plane -- 0 dead
    front, 90 the crown, 180 dead back -- and it is swept MONOTONICALLY. That
    monotonicity is the whole point, and it is the third routing tried here:

      * Walking base vertices gave a MEASURED max turn of 106 degrees. No
        vertex-picking rule can be smoother than the 0.1436 dm mesh it picks
        from.
      * A fixed ellipsoid about the cranium centre is smooth but does not fit
        the occiput: MEASURED, its tail stands 0.25 dm off the surface by
        elevation -45, and projecting those samples collapses them onto the
        region's RIM -- rows stopped 15 to 37 degrees above the hairline at the
        back and left the occiput bare.
      * Marching freely over the surface tracks the occiput but can REVERSE:
        the new direction came from the projected displacement, which snaps
        sideways at a facet, and two rows turned round and went back over the
        crown (max turn 79 degrees).

    So the angle advances on its own and only the RADIUS is carried forward
    from the previous projected point. The head's radius varies slowly, so each
    candidate starts near the surface and the projection is a small correction
    rather than a search -- smooth by construction, and it cannot double back.

    `samples` is a real trade-off, not a free parameter: finer steps amplify
    per-facet jitter into the turn angle. MEASURED over the six rows, the max
    turn between PATH POINTS runs 14.6..21.9 degrees at 40 samples, 17.7..19.8
    at 70 and 19.0..28.9 at 90, while the largest gap between samples falls from
    0.124 dm to 0.070 and then 0.055. 70 is where the rows are smoothest.

    Those are turns between path points. `test_cornrows_shape.cpp` measures
    between RING CENTROIDS and gets larger numbers for the same geometry, for
    the reason stated there -- the two are not comparable and neither is wrong.
    """
    out, r = [], None
    for i in range(samples):
        t = math.radians(t0 + (t1 - t0) * i / (samples - 1))
        if r is None:
            # Settle the first radius before the sweep starts, so the first
            # sample is no worse placed than the rest.
            r = 0.8
            for _ in range(6):
                q, _n, _d = project_to_region(
                    [x, CENTRE[1] + r * math.sin(t), CENTRE[2] + r * math.cos(t)], tris)
                r = math.hypot(q[1] - CENTRE[1], q[2] - CENTRE[2])
        q, nrm, d = project_to_region(
            [x, CENTRE[1] + r * math.sin(t), CENTRE[2] + r * math.cos(t)], tris)
        if d > max_dist:
            # Before the row has started this is the forehead, above the
            # hairline; after it has started it is the rim, and the row is done.
            if out:
                break
            continue
        r = math.hypot(q[1] - CENTRE[1], q[2] - CENTRE[2])
        out.append((q, nrm, d))
    return out


def ridge(path, stand=0.13, half=0.06, sides=6):
    """A rounded ridge swept along one path: the braid itself.

    The frame is the path TANGENT and the true SURFACE NORMAL. A first version
    used the radial direction from the cranium centre and rendering it settled
    the matter: radial is nearly TANGENTIAL where the scalp curves away at
    front and back, so the ring lay flat in the surface and vanished, leaving
    six short spikes at the crown. Radial only behaves like a normal on a
    sphere.

    The ring is pushed fully clear of the skin (`0.55 + 0.45*cos`), because a
    section centred on the surface buries half of itself in the head.
    """
    pts = [p for p, _n, _d in path]
    normals = [n for _p, n, _d in path]
    out, rings, uvs = [], [], []
    for i, p in enumerate(pts):
        nxt = pts[min(i + 1, len(pts) - 1)]
        prv = pts[max(i - 1, 0)]
        t = [nxt[k] - prv[k] for k in range(3)]
        tl = math.sqrt(sum(c * c for c in t)) or 1.0
        t = [c / tl for c in t]
        outward = normals[i]
        side = [t[1] * outward[2] - t[2] * outward[1],
                t[2] * outward[0] - t[0] * outward[2],
                t[0] * outward[1] - t[1] * outward[0]]
        sl = math.sqrt(sum(c * c for c in side)) or 1.0
        side = [c / sl for c in side]
        ring = []
        # `sides + 1` VERTICES PER RING, the last one a duplicate of the first.
        #
        # The ring closes, so the quad joining the last facet back to the first
        # used to run from u = (sides-1)/sides straight to u = 0 -- the long way
        # round -- and a texture sampled across it is the whole 256 px strand
        # sheet squeezed and reversed into one facet column. MEASURED: 42 of
        # 252 brow faces (16.7%, exactly one of six columns), cornrows 16.7%,
        # locs 17.6%. It was harmless while these styles had no texture, and
        # stopped being harmless the moment the brow wore one.
        #
        # A seam needs TWO coordinates at the same place -- one ending at 1.0
        # and one starting at 0.0 -- which no single vertex can carry, because
        # an .obj vertex has one `vt`. So the seam vertex is duplicated: same
        # position, same binding, different u. `write_style` documents the same
        # fix for the afro's unwrap; this is the sweep's version of it.
        for k in range(sides + 1):
            a = 2.0 * math.pi * k / sides
            r = [p[j] + outward[j] * (stand * (0.55 + 0.45 * math.cos(a)))
                 + side[j] * (half * math.sin(a)) for j in range(3)]
            ring.append(len(out))
            out.append(tuple(r))
            # UV, and the whole point of it: a strand texture has to run ALONG
            # the braid, not across it. u goes around the tube and v along the
            # path, so the alpha streaks in `make_hair_alpha.py` line up with
            # the direction hair actually grows. Without this the four
            # generated styles carried no `vt` at all and the material's own
            # note -- "needs an alpha-cut strand texture, which the cage
            # geometry cannot stand in for" -- had nowhere to map it.
            uvs.append((k / float(sides), i / float(max(1, len(pts) - 1))))
        rings.append(ring)
    faces = []
    for i in range(len(rings) - 1):
        for k in range(sides):
            # No modulo any more: the ring carries its own closing vertex, so
            # the last facet reads `k + 1` like every other one. The modulo was
            # the seam.
            a, b = rings[i][k], rings[i][k + 1]
            c, d = rings[i + 1][k + 1], rings[i + 1][k]
            faces.append([a, b, c, d])
    return out, faces, uvs


CORNROW_ROWS = 6


# Bantu knots: a coiled bun at each of a handful of roots spread over the
# cranium. Nine is the count the style is usually worn in, and it is what the
# scalp can hold at this radius without the buns touching -- MEASURED below by
# the closest-pair check, which is the gate.
BANTU_KNOTS = 12
BANTU_RADIUS = 0.24
BANTU_HEIGHT = 0.20
BANTU_SEGMENTS = 10
BANTU_RINGS = 5
# The base ring sits a little UNDER the scalp so the bun meets the head with no
# rim of daylight between them. Small, because the fit is per-vertex and the
# scalp is curved -- sink it far and the bun swallows itself on a flat crown.
BANTU_SINK = 0.03
# The knot's radius as an angle about the cranium centre, which is the frame
# the hairline is measured in: atan(0.24 / ~1.0 dm) is about 14 degrees.
BANTU_INSET_DEG = 14.0
# A thin shell under the knots. Bantu knots are worn on a head OF HAIR -- the
# sections between them are flat hair, not bare scalp -- and without this the
# knots rendered as blobs stuck to a bald head, which is the same "too crude to
# carry the name" the 2026-09-11 attempt stopped at. Reuses `afro`'s shell at a
# fraction of its thickness, so the cap is the proven geometry, not new.
BANTU_CAP = 0.10


def _frame(axis):
    """Two unit vectors across @p axis. Any pair will do -- a bun has no seam
    to align, and the twist below is about the axis, not about these."""
    up = (0.0, 0.0, 1.0) if abs(axis[1]) > 0.9 else (0.0, 1.0, 0.0)
    u = [up[1] * axis[2] - up[2] * axis[1],
         up[2] * axis[0] - up[0] * axis[2],
         up[0] * axis[1] - up[1] * axis[0]]
    lu = math.sqrt(sum(t * t for t in u)) or 1.0
    u = [t / lu for t in u]
    v = [axis[1] * u[2] - axis[2] * u[1],
         axis[2] * u[0] - axis[0] * u[2],
         axis[0] * u[1] - axis[1] * u[0]]
    return u, v


def knot_mesh(root, axis, base):
    """One bun: rings up a dome profile, twisted, closed with a fan to the tip.

    The profile is `sqrt(1 - t^2)` rather than a cone's `1 - t`, because a bantu
    knot is round-shouldered and a cone reads as a spike. The twist is what
    makes it a KNOT rather than a bump -- it is small on purpose, since the
    facets are only eight around and a large twist reads as a shear.
    """
    u, v = _frame(axis)
    pts, faces, uvs = [], [], []
    for ring in range(BANTU_RINGS):
        t = ring / BANTU_RINGS
        radius = BANTU_RADIUS * math.sqrt(max(0.0, 1.0 - t * t))
        rise = BANTU_HEIGHT * t - BANTU_SINK
        twist = 0.45 * t
        # BANTU_SEGMENTS + 1, the last a duplicate of the first: the seam fix
        # `ridge` and `loc_tube` carry. The ring closes, so without a second
        # coordinate at the same place the wrapping facet interpolates u from
        # (n-1)/n back to 0 the long way and smears the strand sheet across it.
        # Measured at 60 of 1,008 bantu faces, 6.0% -- lower than the sweeps
        # only because a knot has more rings than it has facets around.
        #
        # EVERY INDEX BELOW STRIDES BY BANTU_SEGMENTS + 1 as a result, including
        # the tip. Getting one of those wrong does not fail loudly; it stitches
        # the knot to the wrong row.
        for seg in range(BANTU_SEGMENTS + 1):
            a = 2.0 * math.pi * seg / BANTU_SEGMENTS + twist
            pts.append(tuple(root[i] + u[i] * radius * math.cos(a)
                             + v[i] * radius * math.sin(a) + axis[i] * rise
                             for i in range(3)))
            # Around the knot in u, up it in v, so the strand streaks wrap the
            # bun the way the hair is actually wound. The tip below takes v = 1.
            uvs.append((seg / float(BANTU_SEGMENTS), t))
    pts.append(tuple(root[i] + axis[i] * BANTU_HEIGHT for i in range(3)))
    uvs.append((0.5, 1.0))

    stride = BANTU_SEGMENTS + 1
    for ring in range(BANTU_RINGS - 1):
        for seg in range(BANTU_SEGMENTS):
            faces.append([base + ring * stride + seg,
                          base + ring * stride + seg + 1,
                          base + (ring + 1) * stride + seg + 1,
                          base + (ring + 1) * stride + seg])
    tip = base + BANTU_RINGS * stride
    last = base + (BANTU_RINGS - 1) * stride
    for seg in range(BANTU_SEGMENTS):
        faces.append([last + seg, last + seg + 1, tip])
    return pts, faces, uvs


def bantu(verts, body_faces, app_path=""):
    """Knots at roots the APPLICATION spreads over the cranium.

    The roots come from `--spread-roots`, which is farthest-point sampling over
    the scalp SURFACE (`mh::core::spreadOverSurface`). That is the whole reason
    the 2026-09-11 attempt is worth repeating: placing by casting rays from the
    head centre silently collapsed every missed ray onto the scalp rim, so wide
    arrangements piled up at the front edge and two rounds of retuning changed
    nothing.
    """
    app = app_binary(app_path)
    # Ask for MORE than are wanted, because roots on the hairline itself are
    # dropped below. `spreadOverSurface` returns farthest-point order, so any
    # prefix is still spread -- which is what makes "filter, then take the
    # first N" keep the arrangement instead of clumping it.
    out = subprocess.run([app, "--spread-roots", str(BANTU_KNOTS * 4)],
                         capture_output=True, text=True, check=True).stdout
    spread = [tuple(float(t) for t in line.split()[1:4])
              for line in out.splitlines() if line.strip()]

    # A knot is a BALL, so its whole footprint has to be inside the hair, not
    # just its centre: a root sitting on the hairline hangs a 0.24 dm bun over
    # the brow, which RENDERED as a knot on the forehead. The inset is that
    # radius expressed as an angle about the cranium centre, which is what the
    # hairline is measured in.
    roots = [p for p in spread
             if spherical(p)[0] >= hairline(spherical(p)[1]) + BANTU_INSET_DEG][:BANTU_KNOTS]
    if len(roots) != BANTU_KNOTS:
        raise RuntimeError(f"{len(roots)} of {BANTU_KNOTS} roots clear the hairline "
                           f"by {BANTU_INSET_DEG:.0f} deg (spread {len(spread)})")

    # The cap first, so the knots sit ON it. Each of its vertices binds to the
    # base vertex it grew from with a world offset -- the same one-line-per-
    # vertex form `--bind-points` emits, which is why the two can share one
    # .mhclo.
    used, keep, placed = afro(verts, body_faces, thickness=BANTU_CAP)
    cap = {b: i for i, b in enumerate(used)}
    allpts = [tuple(verts[b][i] + placed[b][i] for i in range(3)) for b in used]
    allfaces = [[cap[v] for v in f] for f in keep]
    # The CAP's own UVs. It is cut from the base mesh, whose scalp already has
    # a parameterisation, but these vertices are re-indexed here and the base
    # UVs do not survive that. A planar projection over the cap's extent is
    # enough for a strand texture: the cap is a skullcap under the style, and
    # what has to line up is the braids and knots on top of it.
    _cx = [q[0] for q in allpts] or [0.0]
    _cz = [q[2] for q in allpts] or [0.0]
    _sx = (max(_cx) - min(_cx)) or 1.0
    _sz = (max(_cz) - min(_cz)) or 1.0
    alluvs = [((q[0] - min(_cx)) / _sx, (q[2] - min(_cz)) / _sz) for q in allpts]
    cap_binds = [f"{b} {b} {b} 1.00000 0.00000 0.00000 "
                 f"{placed[b][0]:.5f} {placed[b][1]:.5f} {placed[b][2]:.5f}"
                 for b in used]

    for root in roots:
        # The knot's AXIS, not its placement: placement is the surface walk
        # above. On a cranium this convex the outward direction from the centre
        # and the surface normal agree closely, and unlike a ray it cannot miss.
        axis = [root[i] - CENTRE[i] for i in range(3)]
        la = math.sqrt(sum(t * t for t in axis)) or 1.0
        axis = [t / la for t in axis]
        # Lifted onto the cap, or the knot would sink into the hair it sits on.
        seat = [root[i] + axis[i] * BANTU_CAP for i in range(3)]
        pts, fs, uv = knot_mesh(seat, axis, len(allpts))
        allpts.extend(pts)
        allfaces.extend(fs)
        alluvs.extend(uv)
    return allpts, allfaces, roots, app, cap_binds, len(cap_binds), alluvs


# ---------------------------------------------------------------------------
# Locs.
#
# THREE attempts were reverted before this one and not one of them failed on a
# parameter. The log, because each answer is load-bearing here:
#
#  1. (2026-09-11) Treated the head as a SPHERE and dropped straight down, so
#     every rope was buried in the neck.
#  2. (2026-09-23) Asked the MESH how wide the body is and hung the rope just
#     outside that. Better, and it failed two ways that traded off: following
#     the silhouette flung the side ropes out along the ARMS, and limiting the
#     drift left every rope bunched in a column.
#  3. (2026-09-24) Fixed the flinging -- see `loc_path`, the shelf-versus-wall
#     rule -- and RENDERED ropes hanging across the forehead, eyes and chin,
#     because every rope fell vertically from its own root. Real hair at the
#     hairline is combed BACK.
#
# So a loc is TWO segments, not one: it lies along the scalp from its root to
# the rim -- that is the comb -- and only then hangs. The scalp leg is the
# application's own geodesic (`--scalp-path`), the same Dijkstra cornrows use,
# so the two cannot drift apart.
#
# Measured facts this rests on, all 2026-09-24:
#  * The generator needs NO arm information. Excluding the arm chain leaves 82
#    of 838 path points inside the skin (deepest 1.752 dm) because a rope
#    beside the ear has nothing to land on and falls through the upper arm;
#    the whole body leaves 10 of 766, deepest 0.444, at the same max radius.
#  * The shelf rule is what stops the flinging. CONTROL, rule removed: max
#    radius 2.763 dm. With it: 1.433.

LOC_HALF = 0.06
LOC_SIDES = 5
LOC_STANDOFF = LOC_HALF + 0.02
LOC_STEP = 0.15
# Shoulder-length. The shoulder line is y 5.0..5.5 (`memory/todo.md`).
LOC_FLOOR = 5.85
# The body's vertical axis in x,z: the centroid of torso vertices between y 2.0
# and 6.0. NOT `CENTRE`, which is the CRANIUM centre and the frame the hairline
# is measured in.
BODY_AXIS = (0.0, 0.5481)
LOC_SECTORS = 32
# The lowest point of the hair-bearing scalp, MEASURED and already pinned in
# `tests/check_roots.cmake` (the region's box is y 6.9890..8.4913). Above it the
# rope is in contact with the head; below it it hangs free and can land on
# something.
LOC_SCALP_BOTTOM = 6.98
# The rim the comb runs to: the region's rear, behind the cranium centre and
# below the ear line. MEASURED: 41 of the 237 region vertices, y 6.989..7.367.
LOC_REAR_ELEV = -25.0
# A thin shell under the ropes, for the reason `BANTU_CAP` records: locs are
# worn on a head OF HAIR, and 42 ropes 0.12 dm across cannot cover a scalp 1.5
# dm wide. RENDERED without it, the crown showed as bare red scalp between the
# ropes. Reuses `afro`'s shell at a fraction of its thickness, so the cap is
# proven geometry rather than new.
LOC_CAP = 0.09


def scalp_region(app):
    """The hair-bearing region as {index: position}, from the APPLICATION.

    `--spread-roots 999` is clamped to the whole region, which is how cornrows
    already asks for it -- the definition lives in `mh::core::hairBearingScalp`
    and a second copy here would be free to drift.
    """
    out = subprocess.run([app, "--spread-roots", "999"], capture_output=True,
                         text=True, check=True).stdout
    reg = {}
    for line in out.splitlines():
        if line.strip():
            f = line.split()
            reg[int(f[0])] = tuple(float(t) for t in f[1:4])
    return reg


def scalp_rim(region):
    """The region's lower edge: where a rope leaves the head and starts to hang.

    The elevation cut alone is what keeps the forehead out, and that is
    measured rather than hoped: the hairline sits at +12 degrees of elevation
    at the front, so NO region vertex below -25 is on the face side. An azimuth
    filter was written here as well and excluded exactly 0 of the 41 rim
    vertices, so it was a knob that did nothing and is gone.
    """
    rim = [(i, p) for i, p in region.items() if spherical(p)[0] < LOC_REAR_ELEV]
    if not rim:
        raise RuntimeError("the scalp region has no rim below the hairline")
    return rim


def assign_exits(roots, rim):
    """One rim vertex per rope, nearest first and none used twice.

    THE RIM IS WHAT LIMITS THE STYLE, and this is measured rather than
    asserted. Letting every root take its own nearest rim vertex put 42 ropes
    through 15 exits -- one rim vertex was the target of TEN ropes -- so the
    scalp legs ran on top of each other: 322 chain points with only 137
    distinct, and 2,149 of the asset's 4,095 vertices coincident. Every other
    shipped style has ZERO duplicate positions.

    Overlapping ropes are not merely wasteful. They are why the ropes rendered
    as flat ribbons rather than as separate locs, and half of why the hanging
    mass was no wider than the neck.

    Greedy over all pairs shortest-first: an exact assignment would be the
    Hungarian algorithm, and for a few dozen ropes on a convex scalp the greedy
    answer is the same shape for a tenth of the code.
    """
    pairs = sorted((math.dist(rp, qp), ri, qi)
                   for ri, rp in roots for qi, qp in rim)
    taken, out = set(), {}
    for _d, ri, qi in pairs:
        if ri in out or qi in taken:
            continue
        out[ri] = qi
        taken.add(qi)
    return out


def comb_back(app, root_index, root_pos, target):
    """The scalp leg: the geodesic from a root back to its own rim exit.

    Combing back rather than letting each rope fall from its own root is the
    whole point: MEASURED by rendering, attempt 3 dropped ropes from the
    hairline straight across the face, and removing the comb puts 240 vertices
    there against 0 with it.
    """
    if target == root_index:
        return [root_pos]
    out = subprocess.run([app, "--scalp-path", f"{root_index},{target}"],
                         capture_output=True, text=True, check=True).stdout
    return [tuple(float(t) for t in line.split()[1:4])
            for line in out.splitlines() if line.strip()]


def torso_profile(tris, floor, ceil_):
    """How far the body reaches from its axis, per height and heading.

    A real CROSS-SECTION: every triangle crossing the plane contributes a
    segment, which is then sampled along. Binning vertices instead gave 45
    across 16 sectors at y 5.00, under three each; the section gives 46 to 300
    segments at the same heights.
    """
    ax, az = BODY_AXIS
    rows = []
    y = floor
    while y <= ceil_:
        sec = [0.0] * LOC_SECTORS
        for a, b, c in tris:
            hits = []
            for p, q in ((a, b), (b, c), (c, a)):
                if (p[1] - y) * (q[1] - y) < 0.0:
                    t = (y - p[1]) / (q[1] - p[1])
                    hits.append((p[0] + t * (q[0] - p[0]), p[2] + t * (q[2] - p[2])))
            if len(hits) != 2:
                continue
            (x0, z0), (x1, z1) = hits
            for j in range(9):
                t = j / 8.0
                dx = x0 + t * (x1 - x0) - ax
                dz = z0 + t * (z1 - z0) - az
                k = int((math.degrees(math.atan2(dx, dz)) % 360.0)
                        / (360.0 / LOC_SECTORS))
                sec[k] = max(sec[k], math.hypot(dx, dz))
        rows.append((y, sec))
        y += LOC_STEP
    return rows


def loc_hang(start, profile):
    """The free leg: a plumb line from the rim, pushed out by what is under it.

    No drift limit and no smoothing. `running` is simply the largest thing the
    rope has to clear on the way down -- except that a surface can be a WALL or
    a SHELF, and hair treats them differently. Over one step down the surface
    moves out by `needed - running`; if that exceeds the step itself the
    surface is flatter than 45 degrees, so the rope has LANDED on it and stops.
    A gentler slope is a wall it slides down, staying against it.

    MEASURED, and this is why the rule exists rather than a drift limit:
    without it the ropes were pushed radially out across the top of the
    shoulder to the deltoid's outer face at 2.763 dm. With it, 1.433.
    """
    ax, az = BODY_AXIS
    dx, dz = start[0] - ax, start[2] - az
    theta = math.atan2(dx, dz)
    k = int((math.degrees(theta) % 360.0) / (360.0 / LOC_SECTORS))
    running = math.hypot(dx, dz)
    path = []
    for y, sec in reversed(profile):
        if y > start[1]:
            continue
        needed = sec[k] + LOC_STANDOFF if sec[k] else 0.0
        if y >= LOC_SCALP_BOTTOM:
            running = max(running, needed)
        elif needed > running:
            if needed - running > LOC_STEP:
                break
            running = needed
        path.append((ax + running * math.sin(theta), y,
                     az + running * math.cos(theta)))
    return path


def loc_tube(path, base):
    """A five-sided tube swept along one path."""
    ax, az = BODY_AXIS
    pts, rings, uvs = [], [], []
    for i, p in enumerate(path):
        nxt = path[min(i + 1, len(path) - 1)]
        prv = path[max(i - 1, 0)]
        t = [nxt[j] - prv[j] for j in range(3)]
        tl = math.sqrt(sum(c * c for c in t)) or 1.0
        t = [c / tl for c in t]
        out = [p[0] - ax, 0.0, p[2] - az]
        ol = math.sqrt(sum(c * c for c in out)) or 1.0
        out = [c / ol for c in out]
        side = [t[1] * out[2] - t[2] * out[1], t[2] * out[0] - t[0] * out[2],
                t[0] * out[1] - t[1] * out[0]]
        sl = math.sqrt(sum(c * c for c in side)) or 1.0
        side = [c / sl for c in side]
        ring = []
        # `LOC_SIDES + 1`, the last a duplicate of the first: the same seam fix
        # `ridge` carries, for the same reason. Without it the facet joining the
        # last side back to the first interpolates u the long way and smears the
        # whole strand sheet across it -- measured at 608 of 3,448 loc faces,
        # 17.6%.
        for j in range(LOC_SIDES + 1):
            ang = 2.0 * math.pi * j / LOC_SIDES
            ring.append(base + len(pts))
            pts.append(tuple(p[m] + out[m] * (LOC_HALF * math.cos(ang))
                             + side[m] * (LOC_HALF * math.sin(ang))
                             for m in range(3)))
            # v runs ALONG the loc so the strand streaks hang with it; u goes
            # around. See `ridge` for the same convention.
            uvs.append((j / float(LOC_SIDES), i / float(max(1, len(path) - 1))))
        rings.append(ring)
    faces = []
    for i in range(len(rings) - 1):
        for j in range(LOC_SIDES):
            faces.append([rings[i][j], rings[i][j + 1],
                          rings[i + 1][j + 1], rings[i + 1][j]])
    return pts, faces, uvs


def locs(verts, body_faces, app_path=""):
    """Ropes combed back over the scalp, then hanging down the back."""
    app = app_binary(app_path)
    region = scalp_region(app)
    rim = scalp_rim(region)
    # The COUNT is the rim's, not a number somebody liked: one loc per exit is
    # exactly as many ropes as can hang without lying on top of each other.
    # MEASURED on the shipped mesh, the rim holds 41 vertices.
    out = subprocess.run([app, "--spread-roots", str(len(rim))],
                         capture_output=True, text=True, check=True).stdout
    roots = [(int(l.split()[0]), tuple(float(t) for t in l.split()[1:4]))
             for l in out.splitlines() if l.strip()]
    if len(roots) != len(rim):
        raise RuntimeError(f"{len(roots)} roots for {len(rim)} rim exits")
    exits = assign_exits(roots, rim)

    # The WHOLE body, arms included, and that is measured rather than careless:
    # see the header. The shelf rule, not an exclusion, is what keeps the ropes
    # off the arms.
    tris = [tuple(verts[v] for v in (f[0], f[k], f[k + 1]))
            for f in body_faces for k in range(1, len(f) - 1)]
    profile = torso_profile(tris, LOC_FLOOR, 8.6)

    # The cap first, so the ropes sit ON it. Each of its vertices binds to the
    # base vertex it grew from with a world offset -- the same one-line-per-
    # vertex form `--bind-points` emits, which is why the two share one .mhclo.
    used, keep, placed = afro(verts, body_faces, thickness=LOC_CAP)
    cap = {b: i for i, b in enumerate(used)}
    allpts = [tuple(verts[b][i] + placed[b][i] for i in range(3)) for b in used]
    # How many ropes have already passed through each scalp vertex.
    crossings = collections.defaultdict(int)
    allfaces = [[cap[v] for v in f] for f in keep]
    # The CAP's own UVs. It is cut from the base mesh, whose scalp already has
    # a parameterisation, but these vertices are re-indexed here and the base
    # UVs do not survive that. A planar projection over the cap's extent is
    # enough for a strand texture: the cap is a skullcap under the style, and
    # what has to line up is the braids and knots on top of it.
    _cx = [q[0] for q in allpts] or [0.0]
    _cz = [q[2] for q in allpts] or [0.0]
    _sx = (max(_cx) - min(_cx)) or 1.0
    _sz = (max(_cz) - min(_cz)) or 1.0
    alluvs = [((q[0] - min(_cx)) / _sx, (q[2] - min(_cz)) / _sz) for q in allpts]
    cap_binds = [f"{b} {b} {b} 1.00000 0.00000 0.00000 "
                 f"{placed[b][0]:.5f} {placed[b][1]:.5f} {placed[b][2]:.5f}"
                 for b in used]
    shortest = 10 ** 9
    for index, pos in roots:
        scalp = comb_back(app, index, pos, exits[index])
        # The scalp leg lies ON the head, so it is lifted clear of the skin by
        # the rope's own half width -- a path centred on the surface buries half
        # the tube, which is the mistake `ridge` records.
        lifted = []
        for q in scalp:
            d = [q[i] - CENTRE[i] for i in range(3)]
            ln = math.sqrt(sum(t * t for t in d)) or 1.0
            # Where two ropes cross, the later one passes OVER the earlier, one
            # rope-diameter further out. That is what happens on a real head,
            # and it is also the only thing that stood between this asset and
            # the rest of the tree: MEASURED, every other shipped .obj -- base,
            # tights, cornrows, bantu knots, both eye meshes, skirt, afro,
            # eyelashes, tongue, genitals, teeth -- has EXACTLY ZERO coincident
            # vertex positions, and locs had 13.1% without this. Ropes rooted at
            # the front must travel back across ropes rooted mid-scalp, so the
            # geodesics genuinely share runs of scalp vertices.
            stack = crossings[q]
            crossings[q] = stack + 1
            lift = LOC_CAP + LOC_STANDOFF + stack * 2.0 * LOC_HALF
            lifted.append(tuple(q[i] + d[i] / ln * lift for i in range(3)))
        path = lifted + loc_hang(lifted[-1], profile)
        shortest = min(shortest, len(path))
        if len(path) < 3:
            continue
        pts, fs, uv = loc_tube(path, len(allpts))
        allpts.extend(pts)
        allfaces.extend(fs)
        alluvs.extend(uv)
    return allpts, allfaces, roots, app, shortest, cap_binds, len(cap_binds), alluvs


def cornrows(verts, body_faces, app_path=""):
    """Six rows: the scalp's cross-section at six lateral offsets, each swept.

    Every step is its own function deliberately. The previous `cornrows()`
    scored about 14 against Sonar's cognitive-complexity limit of 15
    (`python:S3776`), so growing it by even one branch fails the gate.
    """
    app = app_binary(app_path)
    # The region comes from the APPLICATION, which owns the definition
    # (`mh::core::hairBearingScalp`). Deriving it here again would be a third
    # copy of the hairline, free to drift from the other two.
    region = [int(line.split()[0])
              for line in subprocess.run([app, "--spread-roots", "999"],
                                         capture_output=True, text=True,
                                         check=True).stdout.splitlines()
              if line.strip()]
    if len(region) < CORNROW_ROWS:
        raise RuntimeError(f"the application returned {len(region)} scalp vertices")
    tris = region_triangles(verts, region, body_faces)
    if not tris:
        raise RuntimeError("no triangle lies wholly inside the scalp region")
    half = crown_half_width(verts, region)

    allpts, allfaces, alluvs, traced = [], [], [], 0
    for i in range(CORNROW_ROWS):
        u = (2.0 * i + 1.0) / CORNROW_ROWS - 1.0
        path = trace_row(tris, CENTRE[0] + half * u)
        if len(path) < 3:
            print(f"cornrows: row {i} traced {len(path)} samples -- dropped", file=sys.stderr)
            continue
        pts, fs, uv = ridge(path)
        base = len(allpts)
        allpts.extend(pts)
        allfaces.extend([[k + base for k in f] for f in fs])
        alluvs.extend(uv)
        traced += 1
    return allpts, allfaces, traced, app, alluvs


if __name__ == "__main__":
    sys.exit(main())
