#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
"""Generates textured-Black hair styles as proxies fitted to the body scalp.

Asked for by the owner: afro (the owner's word is `bambucha`), and later locs,
cornrows and bantu knots. ATTEMPTED 2026-09-11 and not shipped -- five
iterations produced silhouettes too crude to carry the names. `memory/todo.md`
records why, and every number below is measured rather than guessed.

WHAT WENT WRONG LAST TIME, and what is different now:

* Placement raycast from the head centre onto the scalp. The scalp is not a
  closed dome, so a direction grid misses, and the nearest-direction fallback
  silently piled every miss onto the rim. THIS generator never searches for a
  scalp point: it starts from the scalp VERTICES themselves and pushes them
  outward, so there is nothing to miss.
* `helper-hair` was the obvious source and is the wrong one -- it is a long-hair
  envelope carrying ribbons down over the face. The region here is the BODY
  group only.

THE FIT. `fitProxy` (src/core/Proxy.cpp:423-441) computes
    P = SUM w_k * H[v_k] + (m.x*d.x, m.y*d.y, m.z*d.z)
and `TMatrix::diagonal` (src/core/Proxy.cpp:82-84) returns (1,1,1) when the
file declares no scale or shear form -- which this one does not. So `d` is a
plain WORLD-SPACE offset in rest, and a proxy vertex is written as
    <b> <b> <b> 1 0 0 <dx> <dy> <dz>
binding to base vertex b. Rest space is right: fitting runs before skinning
(main.cpp wornSkins), so hair anchored to the scalp follows a head turn free.
"""
import argparse
import math
import sys
import uuid
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "data" / "3dobjs" / "base.obj"
OUT = ROOT / "data" / "hair"
# Styles that are not ready to ship go to the build tree, not to `data/`.
# `data/` IS the shipped asset tree -- `AssetIndex::build` scans it, and a
# half-finished style dropped in there becomes a wearable the moment it is
# written, which is how an unshipped cornrow cage turned the asset-index test
# red on a working copy that had merely RUN the generator.
WORK = ROOT / "build" / "hair"

BANNER = "# Generated by tools/make_hair_styles.py -- do not edit by hand."

# The cranium centre, measured and recorded in `memory/todo.md`.
CENTRE = (0.0, 7.75, 0.50)

# The hairline, in degrees of elevation about CENTRE, as a function of azimuth
# measured from the FRONT (+z). Measured on the base mesh: forehead sits at
# ~+9 degrees in this frame, brow -13, ears -25, nape -50. An earlier attempt
# used `14 + 20*cos(theta)` in a frame 0.2 dm too low and put every style in a
# band across the crown that read as a headband.
def hairline(azim_deg: float) -> float:
    return -19.0 + 31.0 * math.cos(math.radians(azim_deg))


def read_base():
    verts, faces = [], []
    group = ""
    for line in BASE.read_text().splitlines():
        if line.startswith("v "):
            verts.append(tuple(float(t) for t in line.split()[1:4]))
        elif line.startswith("g "):
            group = line.split(None, 1)[1].strip()
        elif line.startswith("f ") and group == "body":
            faces.append([int(p.split("/")[0]) - 1 for p in line.split()[1:]])
    return verts, faces


def spherical(v):
    """Elevation and azimuth of a vertex about CENTRE, in degrees."""
    dx, dy, dz = v[0] - CENTRE[0], v[1] - CENTRE[1], v[2] - CENTRE[2]
    return (math.degrees(math.atan2(dy, math.hypot(dx, dz))),
            math.degrees(math.atan2(dx, dz)))


def afro(verts, faces, thickness=0.78, edge_deg=20.0, skirt_deg=12.0):
    """A rounded shell standing off the scalp: the afro silhouette.

    Every hair-bearing vertex is pushed out along its own surface NORMAL by
    `thickness`, so the shell is a uniform-depth copy of the skull. An earlier
    version grew each vertex RADIALLY from the cranium centre and rendering it
    settled the matter: radial growth only yields a ball if the source is
    already a sphere, and the scalp is not -- low vertices sit far from the
    centre horizontally, so they pushed sideways and the result was a
    wide-brimmed mushroom cap. A normal offset follows the head, which from the
    front reads as the round halo an afro actually is.

    The offset holds FULL volume across the scalp and eases off only in the
    last `edge_deg` degrees before the hairline, so the shell meets the skin
    tangentially at the edge without losing body anywhere else. MEASURED: a
    single mesh edge changes the hairline margin by a median of 7.2 degrees
    (p90 14.4), so a band narrower than that collapses the whole taper into one
    face -- rendering it at 9 degrees produced dark jagged spikes fanning
    around the face. 30 degrees spans about four rows of vertices. A first version
    eased over the whole scalp -- `margin/deepest` -- and rendering it settled
    the matter: mean offset 0.086 dm, 18 px of added height, no added width,
    and it read as a flat-top sitting too far back with a bare forehead. Volume
    has to be near-constant or it is not an afro.
    """
    margin = {}
    for i, v in enumerate(verts):
        elev, azim = spherical(v)
        m = elev - hairline(azim)
        # A SKIRT of vertices below the hairline is kept in the patch with zero
        # growth. Without it the shell's rim IS the region boundary, and that
        # boundary is a ragged polyline of whichever vertices happened to fall
        # inside -- which rendered as serrations along the hairline. With it the
        # grown part ends inside the patch and the rim lies flat on the skin.
        if m > -skirt_deg:
            margin[i] = m
    if not margin:
        return [], [], {}

    # Only whole faces, and only the vertices those faces use: `loadObj`
    # REJECTS a vertex referenced by no face (src/core/ObjReader.cpp:235-243),
    # and the whole proxy then fails to load -- which renders as a bald head
    # rather than as an error any gate would catch.
    keep = [f for f in faces if all(v in margin for v in f)]
    used = sorted({v for f in keep for v in f})

    # Area-weighted vertex normals over the kept patch, flipped outward: the
    # base mesh's winding is not assumed, it is CHECKED against the direction
    # away from the cranium centre.
    normal = {b: [0.0, 0.0, 0.0] for b in used}
    for f in keep:
        a, bb, c = verts[f[0]], verts[f[1]], verts[f[2]]
        u = (bb[0] - a[0], bb[1] - a[1], bb[2] - a[2])
        w = (c[0] - a[0], c[1] - a[1], c[2] - a[2])
        n = (u[1] * w[2] - u[2] * w[1], u[2] * w[0] - u[0] * w[2], u[0] * w[1] - u[1] * w[0])
        for v in f:
            for k in range(3):
                normal[v][k] += n[k]

    placed = {}
    for b in used:
        n = normal[b]
        ln = math.sqrt(sum(t * t for t in n))
        x, y, z = verts[b]
        out = (x - CENTRE[0], y - CENTRE[1], z - CENTRE[2])
        if ln < 1e-9:
            placed[b] = (0.0, 0.0, 0.0)
            continue
        n = [t / ln for t in n]
        if sum(n[k] * out[k] for k in range(3)) < 0.0:
            n = [-t for t in n]
        # smoothstep over a NARROW band at the hairline only.
        t = min(1.0, max(0.0, margin[b]) / edge_deg)
        ease = t * t * (3.0 - 2.0 * t)
        grow = thickness * ease
        placed[b] = (n[0] * grow, n[1] * grow, n[2] * grow)
    return used, keep, placed


def write_style(name, stem, used, keep, placed, verts):
    index = {b: i for i, b in enumerate(used)}
    obj = [BANNER,
           f"# {name}: {len(used)} vertices, {len(keep)} faces.", "g " + stem]
    for b in used:
        x, y, z = verts[b]
        d = placed[b]
        obj.append("v {:.6f} {:.6f} {:.6f}".format(x + d[0], y + d[1], z + d[2]))
    for f in keep:
        obj.append("f " + " ".join(str(index[v] + 1) for v in f))

    mhclo = [
        BANNER,
        "#",
        "# A shell standing off the BODY scalp. Each vertex binds to the base",
        "# vertex it grew from, with a world-space offset: the fit declares no",
        "# scale form, so TMatrix::diagonal is (1,1,1) and the offset applies",
        "# unchanged (src/core/Proxy.cpp:82-84, 423-441).",
        f"name {name}",
        f"uuid 8f2c1d4a-hair-{stem}",
        "basemesh hm08",
        f"obj_file {stem}.obj",
        "material materials/hair.mhmat",
        "z_depth 60",
        "verts 0",
    ]
    for b in used:
        d = placed[b]
        mhclo.append(f"{b} {b} {b} 1.00000 0.00000 0.00000 "
                     f"{d[0]:.5f} {d[1]:.5f} {d[2]:.5f}")
    return "\n".join(obj) + "\n", "\n".join(mhclo) + "\n"


def write_bound_style(name, stem, points, faces, bindings):
    """A style whose geometry is AUTHORED, not cut from the base mesh.

    The .obj carries the authored positions and the .mhclo carries one binding
    per vertex, in the same order -- which is the contract `fitProxy` reads.
    """
    obj = [BANNER,
           f"# {name}: {len(points)} vertices, {len(faces)} faces.", "g " + stem]
    for x, y, z in points:
        obj.append(f"v {x:.6f} {y:.6f} {z:.6f}")
    for f in faces:
        obj.append("f " + " ".join(str(i + 1) for i in f))
    mhclo = [
        BANNER,
        "#",
        "# AUTHORED geometry bound to the body scalp by three base vertices,",
        "# barycentric weights and an offset -- `mh::core::bindToSurface` via",
        "# `--bind-points`. The scalp is only ten vertices across, so rows this",
        "# fine cannot be cut from base vertices.",
        f"name {name}",
        # A REAL uuid, unlike the `8f2c1d4a-hair-<stem>` placeholder the shipped
        # afro still carries: `AssetIndex::findByUuid` is how a saved model
        # names its proxy, so a style that ships with a malformed one can never
        # be reloaded. The afro's is left alone deliberately -- changing an
        # asset's identity orphans every .mhm that already references it, and
        # that is a migration, not a generator fix.
        f"uuid {uuid.uuid5(uuid.NAMESPACE_URL, 'makehuman/hair/' + stem)}",
        "basemesh hm08",
        f"obj_file {stem}.obj",
        "material materials/hair.mhmat",
        "z_depth 60",
        "verts 0",
    ]
    mhclo.extend(bindings)
    return "\n".join(obj) + "\n", "\n".join(mhclo) + "\n"


def hairline_matches_app(verts, faces) -> int:
    """0 if this generator's hairline is the SAME hairline the application walks.

    `mh::core::hairBearingScalp` holds the formula in C++ now, because a braid
    is routed over the region by `pathOverSurface` before any style exists. Two
    copies of a formula drift silently, and the drift would show as an afro
    whose rim sits where no cornrow can start -- so compare the REGIONS, not the
    constants, and let the application be the authority on its own.
    """
    try:
        app = app_binary()
        theirs = {int(line.split()[0])
                  for line in subprocess.run([app, "--spread-roots", "999"],
                                             capture_output=True, text=True,
                                             check=True).stdout.splitlines()
                  if line.strip()}
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        # A MISSING or failing application is not a failure of this check: the
        # release, ASan and TSan CI jobs never build `build/macos-arm64-debug`,
        # which is where `app_binary()` looks, so skipping keeps a missing tool
        # from reddening a suite it says nothing about.
        print(f"hairline: need the built application to compare ({exc}) -- skipped",
              file=sys.stderr)
        return 0
    except (ValueError, IndexError) as exc:
        # Output that is not "index x y z" is a DIFFERENT thing: the application
        # ran and answered something this cannot read. Skipping would let a
        # broken binary read as a pass, and letting the ValueError escape would
        # report it as a crash rather than as a diagnosis.
        print(f"hairline: the application answered something unreadable ({exc})",
              file=sys.stderr)
        return 1
    body = set()
    for f in faces:
        body.update(f)
    ours = {v for v in body
            if spherical(verts[v])[0] >= hairline(spherical(verts[v])[1])}
    if ours != theirs:
        print(f"hairline: this generator selects {len(ours)} scalp vertices, the "
              f"application {len(theirs)}; {len(ours ^ theirs)} differ", file=sys.stderr)
        return 1
    print(f"hairline: {len(ours)} scalp vertices, same set as the application")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="compare the committed assets against a fresh derivation and "
                         "fail if they differ, instead of writing them")
    args = ap.parse_args()

    verts, faces = read_base()
    used, keep, placed = afro(verts, faces)
    obj, mhclo = write_style("Afro", "afro", used, keep, placed, verts)
    wanted = {"afro.obj": obj, "afro.mhclo": mhclo}

    if args.check:
        # The point of this mode: "generated" is a claim LICENSING.md makes
        # about these files, and without a gate it is an aspiration -- a
        # hand-edit to afro.obj would go unnoticed for ever.
        stale = [n for n, text in wanted.items()
                 if not (OUT / n).exists() or (OUT / n).read_text() != text]
        for n in stale:
            print(f"{n} differs from a fresh derivation", file=sys.stderr)
        if stale:
            return 1
        print(f"afro: {len(wanted)} files match a fresh derivation")
        return hairline_matches_app(verts, faces)

    # Cornrows, if the application is available to route and bind them.
    try:
        pts, fs, app = cornrows(verts, faces)
        binds = bind_points(app, pts, OUT.parent.parent / "build" / "cornrow_points.txt")
        if len(binds) == len(pts):
            cobj, cmhclo = write_bound_style("Cornrows", "cornrows", pts, fs, binds)
            WORK.mkdir(parents=True, exist_ok=True)
            (WORK / "cornrows.obj").write_text(cobj)
            (WORK / "cornrows.mhclo").write_text(cmhclo)
            print(f"cornrows: {len(pts)} vertices, {len(fs)} faces, "
                  f"{len(binds)} bindings -> {WORK}")
        else:
            print(f"cornrows: {len(binds)} bindings for {len(pts)} points -- skipped",
                  file=sys.stderr)
    except (subprocess.CalledProcessError, FileNotFoundError) as exc:
        print(f"cornrows: need the built application to route and bind ({exc}) -- skipped",
              file=sys.stderr)

    for n, text in wanted.items():
        (OUT / n).write_text(text)
    grown = [math.dist((0, 0, 0), placed[b]) for b in used]
    print(f"afro: {len(used)} vertices, {len(keep)} faces")
    print(f"  offset 0 at the hairline .. {max(grown):.4f} dm at the crown, "
          f"mean {sum(grown)/len(grown):.4f}")
    return 0




# ---------------------------------------------------------------------------
# Cornrows.
#
# Rows are PATHS over the scalp, not stripes painted on a shell. The base mesh
# cannot carry them as offsets on its own vertices: MEASURED, the hair-bearing
# scalp is 1.504 dm wide with a median edge of 0.1436 dm, about ten vertices
# across, so ridge/gap/ridge allows at most five rows one vertex wide -- a
# corrugated cap. So the geometry is AUTHORED here and bound to the scalp by
# `--bind-points`, which is what the barycentric binder exists for.

import subprocess

APP_ENV = "MH_APP"


def app_binary() -> str:
    """The built application, which owns the scalp walk and the binder.

    Shelling out rather than reimplementing: a second Dijkstra and a second
    barycentric solver in Python would drift from the ones the application
    actually uses, and the drift would show as hair that sits right in the
    generator and wrong in the app.
    """
    import os
    override = os.environ.get(APP_ENV)
    if override:
        return override
    return str(ROOT / "build" / "macos-arm64-debug" / "src" / "app" / "makehuman.app" /
               "Contents" / "MacOS" / "makehuman")


def scalp_path(app: str, first: int, last: int) -> list[int]:
    out = subprocess.run([app, "--scalp-path", f"{first},{last}"],
                         capture_output=True, text=True, check=True).stdout
    return [int(line.split()[0]) for line in out.splitlines() if line.strip()]


def bind_points(app: str, points, tmp: Path) -> list[str]:
    tmp.write_text("".join(f"{x:.6f} {y:.6f} {z:.6f}\n" for x, y, z in points))
    out = subprocess.run([app, "--bind-points", str(tmp)],
                         capture_output=True, text=True, check=True).stdout
    return [line for line in out.splitlines() if line.strip()]


def row_ends(verts, region, bands=6):
    """Front and back endpoints per lateral band: where each row starts and ends.

    The back end is the band's lowest point in ELEVATION about the cranium
    centre, not its lowest in z. An earlier version used z and its docstring
    claimed "every row really does run hairline to nape" on the strength of the
    z spread alone -- which was never the question. MEASURED against the
    hairline after RENDERING the result in Blender: those z-chosen back ends sat
    52 to 57 degrees ABOVE the nape, so six ridges crossed the crown and the
    whole occiput was bare. The front ends were wrong in the other direction,
    3 to 11 degrees BELOW the hairline, on the forehead.
    """
    xs = [verts[v][0] for v in region]
    lo, hi = min(xs), max(xs)
    ends = []
    for i in range(bands):
        a = lo + (hi - lo) * i / bands
        b = lo + (hi - lo) * (i + 1) / bands
        inb = [v for v in region if a <= verts[v][0] < b]
        if not inb:
            continue
        ends.append((max(inb, key=lambda v: verts[v][2]),
                     min(inb, key=lambda v: spherical(verts[v])[0])))
    return ends


def ridge(verts, path, normals, stand=0.13, half=0.06, sides=6):
    """A rounded ridge standing along one path: the braid itself.

    A cross-section of `sides` points is emitted at each path vertex, swept
    along the row. The frame is the path TANGENT and the true SURFACE NORMAL.
    A first version used the radial direction from the cranium centre and
    rendering it settled the matter: radial is nearly TANGENTIAL where the
    scalp curves away at front and back, so the ring lay flat in the surface
    and vanished, leaving six short spikes at the crown. That is the same
    mistake the afro made -- radial only behaves like a normal on a sphere.

    The ring is pushed fully clear of the skin (`0.55 + 0.45*cos`), because a
    section centred on the surface buries half of itself in the head.
    """
    import math as m
    pts = [verts[v] for v in path]
    out = []
    rings = []
    for i, p in enumerate(pts):
        nxt = pts[min(i + 1, len(pts) - 1)]
        prv = pts[max(i - 1, 0)]
        t = [nxt[k] - prv[k] for k in range(3)]
        tl = m.sqrt(sum(c * c for c in t)) or 1.0
        t = [c / tl for c in t]
        outward = normals[path[i]]
        side = [t[1] * outward[2] - t[2] * outward[1],
                t[2] * outward[0] - t[0] * outward[2],
                t[0] * outward[1] - t[1] * outward[0]]
        sl = m.sqrt(sum(c * c for c in side)) or 1.0
        side = [c / sl for c in side]
        ring = []
        for k in range(sides):
            a = 2.0 * m.pi * k / sides
            r = [p[j] + outward[j] * (stand * (0.55 + 0.45 * m.cos(a)))
                 + side[j] * (half * m.sin(a)) for j in range(3)]
            ring.append(len(out))
            out.append(tuple(r))
        rings.append(ring)
    faces = []
    for i in range(len(rings) - 1):
        for k in range(sides):
            a, b = rings[i][k], rings[i][(k + 1) % sides]
            c, d = rings[i + 1][(k + 1) % sides], rings[i + 1][k]
            faces.append([a, b, c, d])
    return out, faces


def cornrows(verts, body_faces):
    """Six rows, routed and bound by the application's own primitives."""
    app = app_binary()
    body = set()
    for f in body_faces:          # read_base already returns BODY faces only
        body.update(f)
    # The region comes from the APPLICATION, which is the thing that will walk
    # it: `--spread-roots` with a count past the region's size returns the whole
    # region, clamped. Deriving it here again would be a third copy.
    region = [int(line.split()[0])
              for line in subprocess.run([app, "--spread-roots", "999"],
                                         capture_output=True, text=True,
                                         check=True).stdout.splitlines()
              if line.strip()]
    # True vertex normals over the body faces, flipped outward -- the frame the
    # ridge is swept in.
    import math as m
    normals = {v: [0.0, 0.0, 0.0] for v in body}
    for f in body_faces:
        a, b, c = verts[f[0]], verts[f[1]], verts[f[2]]
        u = [b[k] - a[k] for k in range(3)]
        w = [c[k] - a[k] for k in range(3)]
        n = [u[1] * w[2] - u[2] * w[1], u[2] * w[0] - u[0] * w[2], u[0] * w[1] - u[1] * w[0]]
        for v in f:
            for k in range(3):
                normals[v][k] += n[k]
    for v, n in normals.items():
        ln = m.sqrt(sum(c * c for c in n)) or 1.0
        n = [c / ln for c in n]
        out = [verts[v][k] - CENTRE[k] for k in range(3)]
        if sum(n[k] * out[k] for k in range(3)) < 0.0:
            n = [-c for c in n]
        normals[v] = n

    allpts, allfaces = [], []
    for first, last in row_ends(verts, region):
        path = scalp_path(app, first, last)
        if len(path) < 3:
            continue
        pts, fs = ridge(verts, path, normals)
        base = len(allpts)
        allpts.extend(pts)
        allfaces.extend([[i + base for i in f] for f in fs])
    return allpts, allfaces, app

if __name__ == "__main__":
    sys.exit(main())
