#!/usr/bin/env python3
"""Generate eye-colour materials by recolouring the shipped iris.

**Why recolour rather than generate from scratch.** `brown_eye.png` is CC0 like
the rest of `data/`, and it carries three things that are tedious and easy to
get wrong: the sclera's blood vessels, the radial fibre structure of the iris,
and an ALPHA-0 disc for the high-poly proxy's cornea. Recolouring keeps all of
them exactly and changes only the hue of the iris, which is the one thing an eye
colour is.

**The mask is measured, not eyeballed.** Iris pixels are the only strongly
saturated ones in the image: at `saturation > 0.35` there are 79,164 of them and
**zero** fall outside the two iris discs, so the sclera's reddish vessels are
untouched by construction. That was checked before this tool was written; the
`--check` mode re-checks it, because a future retouch of the source could break
the assumption silently.

**Luminance is preserved.** Each iris pixel keeps its original value and gets a
new hue and saturation, so the fibre detail that makes an iris read as an iris
survives the recolour. Setting a flat colour instead gives a plastic disc.

**Colours.** Six, the common human range. `brown` is the source and is not
regenerated -- it ships as authored.

Usage:
    ./.venv-mh/bin/python tools/make_eyes.py          # write the materials
    ./.venv-mh/bin/python tools/make_eyes.py --check  # verify, write nothing
"""

from __future__ import annotations

import argparse
import colorsys
import sys
from pathlib import Path

import numpy as np
from PIL import Image

REPO = Path(__file__).resolve().parent.parent
EYES = REPO / "data" / "eyes" / "materials"
SOURCE = EYES / "brown_eye.png"

#: Saturation above which a pixel is iris. Measured: separates the two iris
#: discs from everything else with nothing in between.
IRIS_SATURATION = 0.35

#: name -> (hue in [0,1], saturation multiplier, value multiplier).
#:
#: Hue is absolute; saturation and value scale the ORIGINAL, so a colour cannot
#: flatten the fibre structure. Greys and blues want less saturation than the
#: source brown, which is nearly monochromatic red.
COLOURS = {
    "amber": (0.09, 1.00, 1.30),
    "hazel": (0.11, 0.70, 1.15),
    "green": (0.27, 0.65, 1.10),
    "blue": (0.58, 0.70, 1.25),
    "grey": (0.58, 0.18, 1.20),
}

MHMAT = """# Generated by tools/make_eyes.py -- do not hand-edit.
#
# Released CC0, like the rest of data/. The iris hue is shifted from the shipped
# brown_eye.png; the sclera, its blood vessels and the alpha-0 cornea disc are
# carried over unchanged.

name Eye_{name}
tag eyes
tag procedural

// Copied from brown.mhmat, which these are recolours of. `transparent True` is
// load-bearing: the high-poly proxy's front geometry is a cornea whose texel is
// alpha 0, and without the flag the renderer discards that alpha and paints an
// opaque disc over the iris.
diffuseColor 1.0 1.0 1.0
specularColor 1.0 1.0 1.0
shininess 1.0
transparent True

diffuseTexture {name}_eye.png
"""


def iris_mask(rgb: np.ndarray, alpha: np.ndarray) -> np.ndarray:
    """Pixels belonging to an iris: the strongly saturated ones."""
    mx = rgb.max(2)
    mn = rgb.min(2)
    sat = np.where(mx > 0, (mx - mn) / np.maximum(mx, 1), 0.0)
    return (sat > IRIS_SATURATION) & (alpha > 0)


def recolour(rgb: np.ndarray, mask: np.ndarray, hue: float, sat_mul: float,
             val_mul: float) -> np.ndarray:
    """Returns a copy of @p rgb with the masked pixels moved to @p hue."""
    out = rgb.copy()
    ys, xs = np.nonzero(mask)
    for y, x in zip(ys, xs):
        r, g, b = (c / 255.0 for c in rgb[y, x])
        _, s, v = colorsys.rgb_to_hsv(r, g, b)
        nr, ng, nb = colorsys.hsv_to_rgb(hue, min(s * sat_mul, 1.0), min(v * val_mul, 1.0))
        out[y, x] = [round(nr * 255), round(ng * 255), round(nb * 255)]
    return out


def differences(png: Path, want_rgb: np.ndarray, want_alpha: np.ndarray,
                src_shape: tuple[int, ...]) -> list[str]:
    """How @p png disagrees with what the generator would write.

    Compared as PIXELS, not as file bytes. PNG encoders are not
    byte-reproducible across versions or platforms, so a byte compare would
    fail on CI for a file that is perfectly correct -- and a gate that cries
    wolf gets switched off.
    """
    got = np.asarray(Image.open(png).convert("RGBA")).astype(int)
    if got.shape != src_shape:
        return [f"{png.name}: {got.shape} against the source's {src_shape}"]

    out: list[str] = []
    if not np.array_equal(got[:, :, :3], want_rgb):
        differing = int((got[:, :, :3] != want_rgb).any(2).sum())
        out.append(f"{png.name}: {differing} pixels differ from what the generator produces")
    # The alpha-0 cornea disc is the whole reason these are recolours rather
    # than fresh images; losing it paints an opaque disc over the iris in the
    # high-poly proxy.
    if not np.array_equal(got[:, :, 3], want_alpha):
        out.append(f"{png.name}: the alpha channel differs from the source's")
    return out


def check_generated(src: np.ndarray, rgb: np.ndarray, alpha: np.ndarray,
                    mask: np.ndarray) -> list[str]:
    """Every way the committed eye assets fail to match this generator.

    Existence alone is not enough, and that is all this used to check. A
    generated asset that no longer matches its generator is the failure mode:
    change COLOURS, forget to re-run, and the shipped PNGs stay at the old hue
    while the tool that documents them says otherwise. Same question
    `build_mixamo_superset.py --check` asks of the skeleton.
    """
    problems: list[str] = []
    for name, (hue, sat_mul, val_mul) in COLOURS.items():
        png = EYES / f"{name}_eye.png"
        mat = EYES / f"{name}.mhmat"
        absent = [f for f in (png, mat) if not f.exists()]
        if absent:
            problems += [f"{f.name}: missing" for f in absent]
            continue
        problems += differences(png, recolour(rgb, mask, hue, sat_mul, val_mul), alpha, src.shape)
        if mat.read_text() != MHMAT.format(name=name):
            problems.append(f"{mat.name}: does not match the MHMAT template")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the source and the mask, write nothing")
    args = ap.parse_args()

    if not SOURCE.exists():
        print(f"missing {SOURCE}", file=sys.stderr)
        return 1

    src = np.asarray(Image.open(SOURCE).convert("RGBA")).astype(int)
    rgb, alpha = src[:, :, :3], src[:, :, 3]
    mask = iris_mask(rgb, alpha)

    # The assumption this tool rests on, re-checked every run: every saturated
    # pixel is inside one of the two iris discs. Centres and radius measured
    # from the shipped texture.
    h, w = mask.shape
    yy, xx = np.mgrid[0:h, 0:w]
    near = ((np.hypot(xx - int(0.706 * w), yy - int(0.293 * h)) < 0.17 * w) |
            (np.hypot(xx - int(0.295 * w), yy - int(0.709 * h)) < 0.17 * w))
    stray = int((mask & ~near).sum())
    print(f"iris pixels: {int(mask.sum())}, outside the iris discs: {stray}")
    if stray:
        print("the saturation mask no longer isolates the irises; "
              "recolouring would touch the sclera", file=sys.stderr)
        return 1
    if args.check:
        stale = check_generated(src, rgb, alpha, mask)
        if stale:
            print("generated eye assets are stale:", file=sys.stderr)
            for line in stale:
                print(f"  {line}", file=sys.stderr)
            print(
                "\nRe-run without --check to regenerate:\n"
                "  ./.venv-mh/bin/python tools/make_eyes.py",
                file=sys.stderr,
            )
            return 1
        print(f"ok -- {len(COLOURS)} eye colours match the generator")
        return 0

    for name, (hue, sat_mul, val_mul) in COLOURS.items():
        out = src.copy()
        out[:, :, :3] = recolour(rgb, mask, hue, sat_mul, val_mul)
        Image.fromarray(out.astype(np.uint8), "RGBA").save(EYES / f"{name}_eye.png")
        (EYES / f"{name}.mhmat").write_text(MHMAT.format(name=name))
        print(f"  {name}")
    print(f"wrote {len(COLOURS)} eye colours to {EYES}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
